/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * E-Workflow API
 * API documentation for the E-Workflow service
 * OpenAPI spec version: v1
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
export type GetProcessSearchOptionsParams = {
workflow_key?: string;
};

export type SearchProcessesParams = {
application_name?: string;
workflow_key?: string;
current_step_code?: string;
status?: string;
business_key?: string;
assignee?: string;
};

export type GetClaimableTasksParams = {
username: string;
};

export type UploadBpmnBody = {
  file: Blob;
};

export type UploadBpmnParams = {
resource_name?: string;
uploaded_by: string;
};

export type GetDefinitionsByWorkflowKeyParams = {
workflowKey: string;
};

export interface WorkflowLookupItemResult {
  code?: string;
  name?: string;
}

export interface WorkflowSearchOptionsResult {
  statuses?: string[];
  steps?: WorkflowLookupItemResult[];
  workflows?: WorkflowLookupItemResult[];
}

export interface WorkflowSearchResult {
  assignee?: string;
  /** Full name of the assignee resolved from wf_user.full_name */
  assigneeFullName?: string;
  businessKey?: string;
  completedAt?: string;
  currentStepCode?: string;
  reminderDate?: string;
  taskCreatedAt?: string;
  taskStatus?: string;
  wfInstanceId?: number;
  workflowStatus?: string;
}

export interface WorkflowProgressStepResult {
  currentStep?: boolean;
  endedAt?: string;
  processor?: string;
  /** Full name of the processor resolved from wf_user.full_name */
  processorFullName?: string;
  startedAt?: string;
  status?: string;
  stepCode?: string;
  stepName?: string;
  stepOrder?: number;
  stepType?: string;
}

export interface WorkflowProgressResult {
  businessKey?: string;
  currentStepCode?: string;
  steps?: WorkflowProgressStepResult[];
  totalSteps?: number;
  workflowInstanceId?: number;
  workflowStatus?: string;
}

export interface ClaimableTaskResult {
  businessKey?: string;
  /** Candidate group code when the task is claimable through a group */
  candidateGroupCode?: string;
  /** Candidate group name when the task is claimable through a group */
  candidateGroupName?: string;
  /** How the user can claim the task: directly as a candidate user or through candidate group membership */
  candidateSourceType?: string;
  createdAt?: string;
  currentStepCode?: string;
  dueDate?: string;
  priority?: number;
  taskCode?: string;
  taskId?: number;
  taskName?: string;
  taskStatus?: string;
  workflowInstanceId?: number;
  workflowStatus?: string;
}

export interface ClaimTaskByCandidateRequest {
  /** Claim note */
  comment?: string;
  /**
   * Candidate username claiming the task for themselves
   * @minLength 1
   */
  username: string;
}

export interface ClaimTaskRequest {
  /** User performing the action */
  actionBy?: string;
  /**
   * Assignee username
   * @minLength 1
   */
  assignee: string;
  /** Claim note */
  comment?: string;
}

/**
 * Business data payload stored into task data
 */
export type CompleteTaskRequestData = {[key: string]: unknown};

export interface CompleteTaskRequest {
  /**
   * User completing the task
   * @minLength 1
   */
  actionBy: string;
  /** Completion note */
  comment?: string;
  /** Business data payload stored into task data */
  data?: CompleteTaskRequestData;
}

export interface ReassignTaskRequest {
  /** User performing the reassignment */
  actionBy?: string;
  /**
   * New assignee username
   * @minLength 1
   */
  assignee: string;
  /** Reassignment note */
  comment?: string;
}

export interface WorkflowTaskResult {
  assignee?: string;
  claimedAt?: string;
  completedAt?: string;
  createdAt?: string;
  dueDate?: string;
  id?: number;
  owner?: string;
  priority?: number;
  status?: string;
  stepInstanceId?: number;
  taskCode?: string;
  taskName?: string;
  workflowInstanceId?: number;
}

export interface WorkflowStepInstanceResult {
  endedAt?: string;
  id?: number;
  processedBy?: string;
  startedAt?: string;
  status?: string;
  stepCode?: string;
  stepDefinitionId?: number;
  tasks?: WorkflowTaskResult[];
}

export interface ProcessInstanceResult {
  businessKey?: string;
  currentStepCode?: string;
  endedAt?: string;
  id?: number;
  startedAt?: string;
  startedBy?: string;
  status?: string;
  stepInstances?: WorkflowStepInstanceResult[];
  workflowDefinitionId?: number;
}

/**
 * Detailed form data from frontend to initialize Camunda process variables
 */
export type StartProcessRequestFormData = {[key: string]: unknown};

export interface StartProcessRequest {
  /** Business key that links workflow to business object */
  businessKey?: string;
  /** Detailed form data from frontend to initialize Camunda process variables */
  formData?: StartProcessRequestFormData;
  /**
   * User who starts the workflow
   * @minLength 1
   */
  startedBy: string;
  /**
   * Workflow key to start
   * @minLength 1
   */
  workflowKey: string;
}

export interface WorkflowTaskIdentityLinkResult {
  createdAt?: string;
  groupCode?: string;
  groupId?: number;
  groupName?: string;
  id?: number;
  taskId?: number;
  type?: string;
  userFullName?: string;
  userId?: number;
  username?: string;
}

export interface CreateWorkflowTaskIdentityLinkRequest {
  groupId?: number;
  taskId: number;
  /** @minLength 1 */
  type: string;
  userId?: number;
}

export interface WorkflowDefinitionDeploymentResult {
  camundaDeploymentId?: string;
  camundaProcessDefinitionId?: string;
  camundaProcessDefinitionKey?: string;
  camundaProcessDefinitionVersion?: number;
  createdAt?: string;
  definitionVersion?: number;
  deployedAt?: string;
  deployedBy?: string;
  deploymentStatus?: string;
  failureReason?: string;
  id?: number;
  workflowDefinitionId?: number;
  workflowKey?: string;
}

export interface DeployWorkflowBpmnRequest {
  /**
   * User who deploys the BPMN to Camunda
   * @minLength 1
   */
  deployedBy: string;
}

export interface WorkflowBpmnResult {
  bpmnChecksum?: string;
  createdAt?: string;
  createdBy?: string;
  definitionVersion?: number;
  deployedAt?: string;
  deployedBy?: string;
  deploymentStatus?: string;
  id?: number;
  resourceName?: string;
  updatedAt?: string;
  updatedBy?: string;
  workflowDefinitionId?: number;
  workflowKey?: string;
}

export interface WorkflowStepDefinitionResult {
  conditionExpression?: string;
  createdAt?: string;
  id?: number;
  nextStepCode?: string;
  slaMinutes?: number;
  stepCode?: string;
  stepName?: string;
  stepOrder?: number;
  stepType?: string;
}

export interface WorkflowDefinitionResult {
  active?: boolean;
  applicationName?: string;
  createdAt?: string;
  createdBy?: string;
  description?: string;
  id?: number;
  steps?: WorkflowStepDefinitionResult[];
  updatedAt?: string;
  version?: number;
  workflowKey?: string;
  workflowName?: string;
}

export interface StepDefinitionRequest {
  /** Conditional expression for transition */
  conditionExpression?: string;
  /** Next step code */
  nextStepCode?: string;
  /** SLA in minutes */
  slaMinutes?: number;
  /**
   * Unique step code inside the workflow
   * @minLength 1
   */
  stepCode: string;
  /**
   * Step display name
   * @minLength 1
   */
  stepName: string;
  /** Execution order of the step */
  stepOrder?: number;
  /**
   * Step type
   * @minLength 1
   */
  stepType: string;
}

export interface DeployWorkflowDefinitionRequest {
  /**
   * Application name
   * @minLength 1
   */
  applicationName: string;
  /** User who deploys the workflow */
  createdBy?: string;
  /** Workflow description */
  description?: string;
  /** @minItems 1 */
  steps: StepDefinitionRequest[];
  /**
   * Unique workflow key
   * @minLength 1
   */
  workflowKey: string;
  /**
   * Workflow display name
   * @minLength 1
   */
  workflowName: string;
}

export type ProblemDetailTitle = string | null;

export type ProblemDetailPropertiesAnyOf = {[key: string]: unknown};

export type ProblemDetailProperties = ProblemDetailPropertiesAnyOf | null;

export type ProblemDetailInstance = string | null;

export type ProblemDetailDetail = string | null;

export interface ProblemDetail {
  detail?: ProblemDetailDetail;
  instance?: ProblemDetailInstance;
  properties?: ProblemDetailProperties;
  status?: number;
  title?: ProblemDetailTitle;
  type?: string;
}





  export const getEWorkflowAPI = () => {
/**
 * Return all versions of a workflow definition by workflow key
 * @summary Search definitions by workflow key
 */
const getDefinitionsByWorkflowKey = <TData = AxiosResponse<WorkflowDefinitionResult[]>>(
    params: GetDefinitionsByWorkflowKeyParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/workflow-definitions`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Create a new workflow definition version with its step definitions
 * @summary Deploy workflow definition
 */
const deployDefinition = <TData = AxiosResponse<WorkflowDefinitionResult>>(
    deployWorkflowDefinitionRequest: DeployWorkflowDefinitionRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/workflow-definitions`,
      deployWorkflowDefinitionRequest,options
    );
  }

/**
 * Upload BPMN XML for an existing workflow definition version
 * @summary Upload BPMN source
 */
const uploadBpmn = <TData = AxiosResponse<WorkflowBpmnResult>>(
    definitionId: number,
    uploadBpmnBody: UploadBpmnBody,
    params: UploadBpmnParams, options?: AxiosRequestConfig
 ): Promise<TData> => {const formData = new FormData();
formData.append('file', uploadBpmnBody.file)

    return axios.post(
      `/api/v1/workflow-definitions/${definitionId}/bpmn`,
      formData,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Deploy uploaded BPMN of a workflow definition version to Camunda
 * @summary Deploy BPMN to Camunda
 */
const deployBpmn = <TData = AxiosResponse<WorkflowDefinitionDeploymentResult>>(
    definitionId: number,
    deployWorkflowBpmnRequest: DeployWorkflowBpmnRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/workflow-definitions/${definitionId}/bpmn/deploy`,
      deployWorkflowBpmnRequest,options
    );
  }

/**
 * Assign candidate user or candidate group to a workflow task
 * @summary Create task identity link
 */
const createTaskIdentityLink = <TData = AxiosResponse<WorkflowTaskIdentityLinkResult>>(
    createWorkflowTaskIdentityLinkRequest: CreateWorkflowTaskIdentityLinkRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/tasks/task-identity-links`,
      createWorkflowTaskIdentityLinkRequest,options
    );
  }

/**
 * Start a new process instance using the latest active definition for the workflow key
 * @summary Start process
 */
const startProcess = <TData = AxiosResponse<ProcessInstanceResult>>(
    startProcessRequest: StartProcessRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/processes/startProcess`,
      startProcessRequest,options
    );
  }

/**
 * Reassign an existing task to another assignee and write assignment history
 * @summary Reassign task
 */
const reassignTask = <TData = AxiosResponse<WorkflowTaskResult>>(
    taskId: number,
    reassignTaskRequest: ReassignTaskRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/api/v1/tasks/${taskId}/reassign`,
      reassignTaskRequest,options
    );
  }

/**
 * Complete a task, optionally save task data, and move workflow to the next step
 * @summary Complete task
 */
const completeTask = <TData = AxiosResponse<WorkflowTaskResult>>(
    taskId: number,
    completeTaskRequest: CompleteTaskRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/api/v1/tasks/${taskId}/complete`,
      completeTaskRequest,options
    );
  }

/**
 * Assign a task to an assignee, mark it as claimed, and remove all CANDIDATE identity links of the task after a successful claim
 * @summary Claim task
 */
const claimTask = <TData = AxiosResponse<WorkflowTaskResult>>(
    taskId: number,
    claimTaskRequest: ClaimTaskRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/api/v1/tasks/${taskId}/claim`,
      claimTaskRequest,options
    );
  }

/**
 * Allow claim only when the user is a valid candidate directly or through candidate group membership. After a successful claim, all CANDIDATE identity links of the task are removed
 * @summary Claim task by candidate
 */
const claimTaskByCandidate = <TData = AxiosResponse<WorkflowTaskResult>>(
    taskId: number,
    claimTaskByCandidateRequest: ClaimTaskByCandidateRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/api/v1/tasks/${taskId}/claim-by-candidate`,
      claimTaskByCandidateRequest,options
    );
  }

/**
 * Return workflow definition details by definition id
 * @summary Get workflow definition by id
 */
const getDefinition = <TData = AxiosResponse<WorkflowDefinitionResult>>(
    definitionId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/workflow-definitions/${definitionId}`,options
    );
  }

/**
 * Return deployment history of uploaded BPMN by workflow definition id
 * @summary Get BPMN deployment history
 */
const getDeploymentHistory = <TData = AxiosResponse<WorkflowDefinitionDeploymentResult[]>>(
    definitionId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/workflow-definitions/${definitionId}/bpmn/deployments`,options
    );
  }

/**
 * Get all wf_task_identity_link records for a workflow task
 * @summary List task identity links
 */
const getTaskIdentityLinks = <TData = AxiosResponse<WorkflowTaskIdentityLinkResult[]>>(
    taskId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/tasks/${taskId}/identity-links`,options
    );
  }

/**
 * Return tasks that the user can claim directly as a candidate user or indirectly through candidate group membership. Tasks that are already claimed by another assignee or already completed are excluded
 * @summary Get claimable tasks by user
 */
const getClaimableTasks = <TData = AxiosResponse<ClaimableTaskResult[]>>(
    params: GetClaimableTasksParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/tasks/claimable`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Return workflow instance details including step instances and tasks
 * @summary Get process instance
 */
const getProcessInstance = <TData = AxiosResponse<ProcessInstanceResult>>(
    instanceId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/processes/${instanceId}`,options
    );
  }

/**
 * Return the transaction progress timeline including total steps, step names, processor, current step, and step statuses
 * @summary Get workflow progress
 */
const getProgress = <TData = AxiosResponse<WorkflowProgressResult>>(
    instanceId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/processes/${instanceId}/progress`,options
    );
  }

/**
 * Search runtime workflow data by application name, workflow key, current step, workflow status, business key, and assignee
 * @summary Search workflow tasks
 */
const searchProcesses = <TData = AxiosResponse<WorkflowSearchResult[]>>(
    params?: SearchProcessesParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/processes/search`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Return lookup data for workflow, step, and status dropdowns used by the search UI
 * @summary Get workflow search options
 */
const getProcessSearchOptions = <TData = AxiosResponse<WorkflowSearchOptionsResult>>(
    params?: GetProcessSearchOptionsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/processes/search-options`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Delete a wf_task_identity_link record
 * @summary Delete task identity link
 */
const deleteTaskIdentityLink = <TData = AxiosResponse<void>>(
    identityLinkId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/v1/tasks/task-identity-links/${identityLinkId}`,options
    );
  }

return {getDefinitionsByWorkflowKey,deployDefinition,uploadBpmn,deployBpmn,createTaskIdentityLink,startProcess,reassignTask,completeTask,claimTask,claimTaskByCandidate,getDefinition,getDeploymentHistory,getTaskIdentityLinks,getClaimableTasks,getProcessInstance,getProgress,searchProcesses,getProcessSearchOptions,deleteTaskIdentityLink}};
export type GetDefinitionsByWorkflowKeyResult = AxiosResponse<WorkflowDefinitionResult[]>
export type DeployDefinitionResult = AxiosResponse<WorkflowDefinitionResult>
export type UploadBpmnResult = AxiosResponse<WorkflowBpmnResult>
export type DeployBpmnResult = AxiosResponse<WorkflowDefinitionDeploymentResult>
export type CreateTaskIdentityLinkResult = AxiosResponse<WorkflowTaskIdentityLinkResult>
export type StartProcessResult = AxiosResponse<ProcessInstanceResult>
export type ReassignTaskResult = AxiosResponse<WorkflowTaskResult>
export type CompleteTaskResult = AxiosResponse<WorkflowTaskResult>
export type ClaimTaskResult = AxiosResponse<WorkflowTaskResult>
export type ClaimTaskByCandidateResult = AxiosResponse<WorkflowTaskResult>
export type GetDefinitionResult = AxiosResponse<WorkflowDefinitionResult>
export type GetDeploymentHistoryResult = AxiosResponse<WorkflowDefinitionDeploymentResult[]>
export type GetTaskIdentityLinksResult = AxiosResponse<WorkflowTaskIdentityLinkResult[]>
export type GetClaimableTasksResult = AxiosResponse<ClaimableTaskResult[]>
export type GetProcessInstanceResult = AxiosResponse<ProcessInstanceResult>
export type GetProgressResult = AxiosResponse<WorkflowProgressResult>
export type SearchProcessesResult = AxiosResponse<WorkflowSearchResult[]>
export type GetProcessSearchOptionsResult = AxiosResponse<WorkflowSearchOptionsResult>
export type DeleteTaskIdentityLinkResult = AxiosResponse<void>
