/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * E-Workflow API
 * API documentation for the E-Workflow service
 * OpenAPI spec version: v1
 */
import { orvalMutator } from '../../lib/orvalMutator';
/**
 * @nullable
 */
export type ProblemDetailProperties = {[key: string]: unknown} | null;

export interface ProblemDetail {
  type?: string;
  /** @nullable */
  title?: string | null;
  status?: number;
  /** @nullable */
  detail?: string | null;
  /** @nullable */
  instance?: string | null;
  /** @nullable */
  properties?: ProblemDetailProperties;
}

export interface StepDefinitionRequest {
  /**
     * Step display name
     * @minLength 1
     */
  stepName: string;
  /**
     * Unique step code inside the workflow
     * @minLength 1
     */
  stepCode: string;
  /**
     * Step type
     * @minLength 1
     */
  stepType: string;
  /** Execution order of the step */
  stepOrder?: number;
  /** Next step code */
  nextStepCode?: string;
  /** Conditional expression for transition */
  conditionExpression?: string;
  /** SLA in minutes */
  slaMinutes?: number;
}

export interface DeployWorkflowDefinitionRequest {
  /**
     * Application name
     * @minLength 1
     */
  applicationName: string;
  /**
     * Workflow display name
     * @minLength 1
     */
  workflowName: string;
  /**
     * Unique workflow key
     * @minLength 1
     */
  workflowKey: string;
  /** Workflow description */
  description?: string;
  /** User who deploys the workflow */
  createdBy?: string;
  /** @minItems 1 */
  steps: StepDefinitionRequest[];
}

export interface WorkflowStepDefinitionResult {
  id?: number;
  stepName?: string;
  stepCode?: string;
  stepType?: string;
  stepOrder?: number;
  nextStepCode?: string;
  conditionExpression?: string;
  slaMinutes?: number;
  createdAt?: string;
}

export interface WorkflowDefinitionResult {
  id?: number;
  applicationName?: string;
  workflowName?: string;
  workflowKey?: string;
  version?: number;
  description?: string;
  active?: boolean;
  createdBy?: string;
  createdAt?: string;
  updatedAt?: string;
  steps?: WorkflowStepDefinitionResult[];
}

export interface WorkflowBpmnResult {
  id?: number;
  workflowDefinitionId?: number;
  workflowKey?: string;
  definitionVersion?: number;
  resourceName?: string;
  deploymentStatus?: string;
  bpmnChecksum?: string;
  createdAt?: string;
  createdBy?: string;
  updatedAt?: string;
  updatedBy?: string;
  deployedAt?: string;
  deployedBy?: string;
}

export interface DeployWorkflowBpmnRequest {
  /**
     * User who deploys the BPMN to Camunda
     * @minLength 1
     */
  deployedBy: string;
}

export interface WorkflowDefinitionDeploymentResult {
  id?: number;
  workflowDefinitionId?: number;
  workflowKey?: string;
  definitionVersion?: number;
  deploymentStatus?: string;
  camundaDeploymentId?: string;
  camundaProcessDefinitionId?: string;
  camundaProcessDefinitionKey?: string;
  camundaProcessDefinitionVersion?: number;
  createdAt?: string;
  deployedAt?: string;
  deployedBy?: string;
  failureReason?: string;
}

export interface CreateWorkflowTaskIdentityLinkRequest {
  taskId: number;
  userId?: number;
  groupId?: number;
  /** @minLength 1 */
  type: string;
}

export interface WorkflowTaskIdentityLinkResult {
  id?: number;
  taskId?: number;
  userId?: number;
  username?: string;
  userFullName?: string;
  groupId?: number;
  groupCode?: string;
  groupName?: string;
  type?: string;
  createdAt?: string;
}

/**
 * Detailed form data from frontend to initialize Camunda process variables
 */
export type StartProcessRequestFormData = {[key: string]: unknown};

export interface StartProcessRequest {
  /**
     * Workflow key to start
     * @minLength 1
     */
  workflowKey: string;
  /** Business key that links workflow to business object */
  businessKey?: string;
  /**
     * User who starts the workflow
     * @minLength 1
     */
  startedBy: string;
  /** Detailed form data from frontend to initialize Camunda process variables */
  formData?: StartProcessRequestFormData;
}

export interface WorkflowTaskResult {
  id?: number;
  workflowInstanceId?: number;
  stepInstanceId?: number;
  taskName?: string;
  taskCode?: string;
  assignee?: string;
  owner?: string;
  status?: string;
  priority?: number;
  dueDate?: string;
  createdAt?: string;
  claimedAt?: string;
  completedAt?: string;
}

export interface WorkflowStepInstanceResult {
  id?: number;
  stepDefinitionId?: number;
  stepCode?: string;
  status?: string;
  processedBy?: string;
  startedAt?: string;
  endedAt?: string;
  tasks?: WorkflowTaskResult[];
}

export interface ProcessInstanceResult {
  id?: number;
  workflowDefinitionId?: number;
  businessKey?: string;
  status?: string;
  currentStepCode?: string;
  startedBy?: string;
  startedAt?: string;
  endedAt?: string;
  stepInstances?: WorkflowStepInstanceResult[];
}

export interface ReassignTaskRequest {
  /**
     * New assignee username
     * @minLength 1
     */
  assignee: string;
  /** User performing the reassignment */
  actionBy?: string;
  /** Reassignment note */
  comment?: string;
}

/**
 * Business data payload stored into task data
 */
export type CompleteTaskRequestData = {[key: string]: unknown};

export interface CompleteTaskRequest {
  /**
     * User completing the task
     * @minLength 1
     */
  actionBy: string;
  /** Completion note */
  comment?: string;
  /** Business data payload stored into task data */
  data?: CompleteTaskRequestData;
}

export interface ClaimTaskRequest {
  /**
     * Assignee username
     * @minLength 1
     */
  assignee: string;
  /** User performing the action */
  actionBy?: string;
  /** Claim note */
  comment?: string;
}

export interface ClaimTaskByCandidateRequest {
  /**
     * Candidate username claiming the task for themselves
     * @minLength 1
     */
  username: string;
  /** Claim note */
  comment?: string;
}

export interface ClaimableTaskResult {
  taskId?: number;
  workflowInstanceId?: number;
  businessKey?: string;
  workflowStatus?: string;
  currentStepCode?: string;
  taskName?: string;
  taskCode?: string;
  taskStatus?: string;
  priority?: number;
  dueDate?: string;
  createdAt?: string;
  /** How the user can claim the task: directly as a candidate user or through candidate group membership */
  candidateSourceType?: string;
  /** Candidate group code when the task is claimable through a group */
  candidateGroupCode?: string;
  /** Candidate group name when the task is claimable through a group */
  candidateGroupName?: string;
}

export interface WorkflowProgressStepResult {
  stepOrder?: number;
  stepCode?: string;
  stepName?: string;
  stepType?: string;
  processor?: string;
  /** Full name of the processor resolved from wf_user.full_name */
  processorFullName?: string;
  status?: string;
  currentStep?: boolean;
  startedAt?: string;
  endedAt?: string;
}

export interface WorkflowProgressResult {
  workflowInstanceId?: number;
  businessKey?: string;
  workflowStatus?: string;
  currentStepCode?: string;
  totalSteps?: number;
  steps?: WorkflowProgressStepResult[];
}

export interface WorkflowSearchResult {
  wfInstanceId?: number;
  businessKey?: string;
  workflowStatus?: string;
  currentStepCode?: string;
  assignee?: string;
  /** Full name of the assignee resolved from wf_user.full_name */
  assigneeFullName?: string;
  taskStatus?: string;
  reminderDate?: string;
  taskCreatedAt?: string;
  completedAt?: string;
}

export interface WorkflowLookupItemResult {
  code?: string;
  name?: string;
}

export interface WorkflowSearchOptionsResult {
  workflows?: WorkflowLookupItemResult[];
  steps?: WorkflowLookupItemResult[];
  statuses?: string[];
}

export type GetDefinitionsByWorkflowKeyParams = {
workflowKey: string;
};

export type UploadBpmnParams = {
resource_name?: string;
uploaded_by: string;
};

export type UploadBpmnBody = {
  file: Blob;
};

export type GetClaimableTasksParams = {
username: string;
};

export type SearchProcessesParams = {
application_name?: string;
workflow_key?: string;
current_step_code?: string;
status?: string;
business_key?: string;
assignee?: string;
};

export type GetProcessSearchOptionsParams = {
workflow_key?: string;
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getEWorkflowAPI = () => {
/**
 * Return all versions of a workflow definition by workflow key
 * @summary Search definitions by workflow key
 */
const getDefinitionsByWorkflowKey = (
    params: GetDefinitionsByWorkflowKeyParams,
 options?: SecondParameter<typeof orvalMutator<WorkflowDefinitionResult[]>>,) => {
      return orvalMutator<WorkflowDefinitionResult[]>(
      {url: `/api/v1/workflow-definitions`, method: 'GET',
        params
    },
      options);
    }

/**
 * Create a new workflow definition version with its step definitions
 * @summary Deploy workflow definition
 */
const deployDefinition = (
    deployWorkflowDefinitionRequest: DeployWorkflowDefinitionRequest,
 options?: SecondParameter<typeof orvalMutator<WorkflowDefinitionResult>>,) => {
      return orvalMutator<WorkflowDefinitionResult>(
      {url: `/api/v1/workflow-definitions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deployWorkflowDefinitionRequest
    },
      options);
    }

/**
 * Upload BPMN XML for an existing workflow definition version
 * @summary Upload BPMN source
 */
const uploadBpmn = (
    definitionId: number,
    params: UploadBpmnParams,
    uploadBpmnBody?: UploadBpmnBody,
 options?: SecondParameter<typeof orvalMutator<WorkflowBpmnResult>>,) => {const formData = new FormData();
if(uploadBpmnBody?.file !== undefined) {
 formData.append(`file`, uploadBpmnBody.file);
 }

      return orvalMutator<WorkflowBpmnResult>(
      {url: `/api/v1/workflow-definitions/${definitionId}/bpmn`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData,
        params
    },
      options);
    }

/**
 * Deploy uploaded BPMN of a workflow definition version to Camunda
 * @summary Deploy BPMN to Camunda
 */
const deployBpmn = (
    definitionId: number,
    deployWorkflowBpmnRequest: DeployWorkflowBpmnRequest,
 options?: SecondParameter<typeof orvalMutator<WorkflowDefinitionDeploymentResult>>,) => {
      return orvalMutator<WorkflowDefinitionDeploymentResult>(
      {url: `/api/v1/workflow-definitions/${definitionId}/bpmn/deploy`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deployWorkflowBpmnRequest
    },
      options);
    }

/**
 * Assign candidate user or candidate group to a workflow task
 * @summary Create task identity link
 */
const createTaskIdentityLink = (
    createWorkflowTaskIdentityLinkRequest: CreateWorkflowTaskIdentityLinkRequest,
 options?: SecondParameter<typeof orvalMutator<WorkflowTaskIdentityLinkResult>>,) => {
      return orvalMutator<WorkflowTaskIdentityLinkResult>(
      {url: `/api/v1/tasks/task-identity-links`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createWorkflowTaskIdentityLinkRequest
    },
      options);
    }

/**
 * Start a new process instance using the latest active definition for the workflow key
 * @summary Start process
 */
const startProcess = (
    startProcessRequest: StartProcessRequest,
 options?: SecondParameter<typeof orvalMutator<ProcessInstanceResult>>,) => {
      return orvalMutator<ProcessInstanceResult>(
      {url: `/api/v1/processes/startProcess`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: startProcessRequest
    },
      options);
    }

/**
 * Reassign an existing task to another assignee and write assignment history
 * @summary Reassign task
 */
const reassignTask = (
    taskId: number,
    reassignTaskRequest: ReassignTaskRequest,
 options?: SecondParameter<typeof orvalMutator<WorkflowTaskResult>>,) => {
      return orvalMutator<WorkflowTaskResult>(
      {url: `/api/v1/tasks/${taskId}/reassign`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: reassignTaskRequest
    },
      options);
    }

/**
 * Complete a task, optionally save task data, and move workflow to the next step
 * @summary Complete task
 */
const completeTask = (
    taskId: number,
    completeTaskRequest: CompleteTaskRequest,
 options?: SecondParameter<typeof orvalMutator<WorkflowTaskResult>>,) => {
      return orvalMutator<WorkflowTaskResult>(
      {url: `/api/v1/tasks/${taskId}/complete`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: completeTaskRequest
    },
      options);
    }

/**
 * Assign a task to an assignee, mark it as claimed, and remove all CANDIDATE identity links of the task after a successful claim
 * @summary Claim task
 */
const claimTask = (
    taskId: number,
    claimTaskRequest: ClaimTaskRequest,
 options?: SecondParameter<typeof orvalMutator<WorkflowTaskResult>>,) => {
      return orvalMutator<WorkflowTaskResult>(
      {url: `/api/v1/tasks/${taskId}/claim`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: claimTaskRequest
    },
      options);
    }

/**
 * Allow claim only when the user is a valid candidate directly or through candidate group membership. After a successful claim, all CANDIDATE identity links of the task are removed
 * @summary Claim task by candidate
 */
const claimTaskByCandidate = (
    taskId: number,
    claimTaskByCandidateRequest: ClaimTaskByCandidateRequest,
 options?: SecondParameter<typeof orvalMutator<WorkflowTaskResult>>,) => {
      return orvalMutator<WorkflowTaskResult>(
      {url: `/api/v1/tasks/${taskId}/claim-by-candidate`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: claimTaskByCandidateRequest
    },
      options);
    }

/**
 * Return workflow definition details by definition id
 * @summary Get workflow definition by id
 */
const getDefinition = (
    definitionId: number,
 options?: SecondParameter<typeof orvalMutator<WorkflowDefinitionResult>>,) => {
      return orvalMutator<WorkflowDefinitionResult>(
      {url: `/api/v1/workflow-definitions/${definitionId}`, method: 'GET'
    },
      options);
    }

/**
 * Return deployment history of uploaded BPMN by workflow definition id
 * @summary Get BPMN deployment history
 */
const getDeploymentHistory = (
    definitionId: number,
 options?: SecondParameter<typeof orvalMutator<WorkflowDefinitionDeploymentResult[]>>,) => {
      return orvalMutator<WorkflowDefinitionDeploymentResult[]>(
      {url: `/api/v1/workflow-definitions/${definitionId}/bpmn/deployments`, method: 'GET'
    },
      options);
    }

/**
 * Get all wf_task_identity_link records for a workflow task
 * @summary List task identity links
 */
const getTaskIdentityLinks = (
    taskId: number,
 options?: SecondParameter<typeof orvalMutator<WorkflowTaskIdentityLinkResult[]>>,) => {
      return orvalMutator<WorkflowTaskIdentityLinkResult[]>(
      {url: `/api/v1/tasks/${taskId}/identity-links`, method: 'GET'
    },
      options);
    }

/**
 * Return tasks that the user can claim directly as a candidate user or indirectly through candidate group membership. Tasks that are already claimed by another assignee or already completed are excluded
 * @summary Get claimable tasks by user
 */
const getClaimableTasks = (
    params: GetClaimableTasksParams,
 options?: SecondParameter<typeof orvalMutator<ClaimableTaskResult[]>>,) => {
      return orvalMutator<ClaimableTaskResult[]>(
      {url: `/api/v1/tasks/claimable`, method: 'GET',
        params
    },
      options);
    }

/**
 * Return workflow instance details including step instances and tasks
 * @summary Get process instance
 */
const getProcessInstance = (
    instanceId: number,
 options?: SecondParameter<typeof orvalMutator<ProcessInstanceResult>>,) => {
      return orvalMutator<ProcessInstanceResult>(
      {url: `/api/v1/processes/${instanceId}`, method: 'GET'
    },
      options);
    }

/**
 * Return the transaction progress timeline including total steps, step names, processor, current step, and step statuses
 * @summary Get workflow progress
 */
const getProgress = (
    instanceId: number,
 options?: SecondParameter<typeof orvalMutator<WorkflowProgressResult>>,) => {
      return orvalMutator<WorkflowProgressResult>(
      {url: `/api/v1/processes/${instanceId}/progress`, method: 'GET'
    },
      options);
    }

/**
 * Search runtime workflow data by application name, workflow key, current step, workflow status, business key, and assignee
 * @summary Search workflow tasks
 */
const searchProcesses = (
    params?: SearchProcessesParams,
 options?: SecondParameter<typeof orvalMutator<WorkflowSearchResult[]>>,) => {
      return orvalMutator<WorkflowSearchResult[]>(
      {url: `/api/v1/processes/search`, method: 'GET',
        params
    },
      options);
    }

/**
 * Return lookup data for workflow, step, and status dropdowns used by the search UI
 * @summary Get workflow search options
 */
const getProcessSearchOptions = (
    params?: GetProcessSearchOptionsParams,
 options?: SecondParameter<typeof orvalMutator<WorkflowSearchOptionsResult>>,) => {
      return orvalMutator<WorkflowSearchOptionsResult>(
      {url: `/api/v1/processes/search-options`, method: 'GET',
        params
    },
      options);
    }

/**
 * Delete a wf_task_identity_link record
 * @summary Delete task identity link
 */
const deleteTaskIdentityLink = (
    identityLinkId: number,
 options?: SecondParameter<typeof orvalMutator<void>>,) => {
      return orvalMutator<void>(
      {url: `/api/v1/tasks/task-identity-links/${identityLinkId}`, method: 'DELETE'
    },
      options);
    }

return {getDefinitionsByWorkflowKey,deployDefinition,uploadBpmn,deployBpmn,createTaskIdentityLink,startProcess,reassignTask,completeTask,claimTask,claimTaskByCandidate,getDefinition,getDeploymentHistory,getTaskIdentityLinks,getClaimableTasks,getProcessInstance,getProgress,searchProcesses,getProcessSearchOptions,deleteTaskIdentityLink}};
export type GetDefinitionsByWorkflowKeyResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEWorkflowAPI>['getDefinitionsByWorkflowKey']>>>
export type DeployDefinitionResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEWorkflowAPI>['deployDefinition']>>>
export type UploadBpmnResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEWorkflowAPI>['uploadBpmn']>>>
export type DeployBpmnResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEWorkflowAPI>['deployBpmn']>>>
export type CreateTaskIdentityLinkResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEWorkflowAPI>['createTaskIdentityLink']>>>
export type StartProcessResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEWorkflowAPI>['startProcess']>>>
export type ReassignTaskResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEWorkflowAPI>['reassignTask']>>>
export type CompleteTaskResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEWorkflowAPI>['completeTask']>>>
export type ClaimTaskResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEWorkflowAPI>['claimTask']>>>
export type ClaimTaskByCandidateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEWorkflowAPI>['claimTaskByCandidate']>>>
export type GetDefinitionResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEWorkflowAPI>['getDefinition']>>>
export type GetDeploymentHistoryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEWorkflowAPI>['getDeploymentHistory']>>>
export type GetTaskIdentityLinksResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEWorkflowAPI>['getTaskIdentityLinks']>>>
export type GetClaimableTasksResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEWorkflowAPI>['getClaimableTasks']>>>
export type GetProcessInstanceResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEWorkflowAPI>['getProcessInstance']>>>
export type GetProgressResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEWorkflowAPI>['getProgress']>>>
export type SearchProcessesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEWorkflowAPI>['searchProcesses']>>>
export type GetProcessSearchOptionsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEWorkflowAPI>['getProcessSearchOptions']>>>
export type DeleteTaskIdentityLinkResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEWorkflowAPI>['deleteTaskIdentityLink']>>>
