/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * E-Connector API
 * Connector Platform API
 * OpenAPI spec version: 1.0
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
export type GetSchema1200 = {[key: string]: unknown};

export type FindAll8200 = {[key: string]: EnumOptionResponse[]};

export type FindAll7Params = {
/**
 * Zero-based page index (0..N)
 */
page?: number;
/**
 * The size of the page to be returned
 */
size?: number;
/**
 * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
 */
sort?: string[];
};

export type GetSchema200 = {[key: string]: unknown};

export type FindAll6Params = {
/**
 * Zero-based page index (0..N)
 */
page?: number;
/**
 * The size of the page to be returned
 */
size?: number;
/**
 * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
 */
sort?: string[];
};

export type FindAll5Params = {
/**
 * Zero-based page index (0..N)
 */
page?: number;
/**
 * The size of the page to be returned
 */
size?: number;
/**
 * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
 */
sort?: string[];
};

export type FindAll4Params = {
/**
 * Zero-based page index (0..N)
 */
page?: number;
/**
 * The size of the page to be returned
 */
size?: number;
/**
 * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
 */
sort?: string[];
};

export type FindAll3Params = {
/**
 * Zero-based page index (0..N)
 */
page?: number;
/**
 * The size of the page to be returned
 */
size?: number;
/**
 * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
 */
sort?: string[];
};

export type FindAll2Params = {
/**
 * Zero-based page index (0..N)
 */
page?: number;
/**
 * The size of the page to be returned
 */
size?: number;
/**
 * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
 */
sort?: string[];
};

export type FindAll1Params = {
/**
 * Zero-based page index (0..N)
 */
page?: number;
/**
 * The size of the page to be returned
 */
size?: number;
/**
 * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
 */
sort?: string[];
};

export type FindAllParams = {
/**
 * Zero-based page index (0..N)
 */
page?: number;
/**
 * The size of the page to be returned
 */
size?: number;
/**
 * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
 */
sort?: string[];
};

export interface EnumOptionResponse {
  label?: string;
  value?: string;
}

export interface LogResult {
  correlationId?: string;
  createdAt?: string;
  durationMs?: number;
  errorMessage?: string;
  id?: number;
  requestAfterTransform?: string;
  requestBody?: string;
  requestHeaders?: string;
  requestTime?: string;
  responseAfterTransform?: string;
  responseBody?: string;
  responseTime?: string;
  serviceId?: number;
  stacktrace?: string;
  statusCode?: number;
  traceId?: string;
}

export interface SortObject {
  empty?: boolean;
  sorted?: boolean;
  unsorted?: boolean;
}

export interface PageableObject {
  offset?: number;
  paged?: boolean;
  pageNumber?: number;
  pageSize?: number;
  sort?: SortObject;
  unpaged?: boolean;
}

export interface PageConnectionResult {
  content?: ConnectionResult[];
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  pageable?: PageableObject;
  size?: number;
  sort?: SortObject;
  totalElements?: number;
  totalPages?: number;
}

export interface PageEmailTemplateResult {
  content?: EmailTemplateResult[];
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  pageable?: PageableObject;
  size?: number;
  sort?: SortObject;
  totalElements?: number;
  totalPages?: number;
}

export interface PageJobExecutionResult {
  content?: JobExecutionResult[];
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  pageable?: PageableObject;
  size?: number;
  sort?: SortObject;
  totalElements?: number;
  totalPages?: number;
}

export interface PageLogResult {
  content?: LogResult[];
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  pageable?: PageableObject;
  size?: number;
  sort?: SortObject;
  totalElements?: number;
  totalPages?: number;
}

export interface PagePipelineStepResult {
  content?: PipelineStepResult[];
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  pageable?: PageableObject;
  size?: number;
  sort?: SortObject;
  totalElements?: number;
  totalPages?: number;
}

export interface PagePipelineResult {
  content?: PipelineResult[];
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  pageable?: PageableObject;
  size?: number;
  sort?: SortObject;
  totalElements?: number;
  totalPages?: number;
}

export interface PageScheduleJobResult {
  content?: ScheduleJobResult[];
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  pageable?: PageableObject;
  size?: number;
  sort?: SortObject;
  totalElements?: number;
  totalPages?: number;
}

export interface PageServiceResult {
  content?: ServiceResult[];
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  pageable?: PageableObject;
  size?: number;
  sort?: SortObject;
  totalElements?: number;
  totalPages?: number;
}

export type CreateConnectionRequestConnectionType = typeof CreateConnectionRequestConnectionType[keyof typeof CreateConnectionRequestConnectionType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateConnectionRequestConnectionType = {
  DB: 'DB',
  REST: 'REST',
  SOAP: 'SOAP',
  SFTP: 'SFTP',
  SMTP: 'SMTP',
  KAFKA: 'KAFKA',
} as const;

export type CreateConnectionRequestConfig = {[key: string]: unknown};

export interface CreateConnectionRequest {
  active?: boolean;
  config?: CreateConnectionRequestConfig;
  /**
   * @minLength 0
   * @maxLength 100
   */
  connectionCode: string;
  /**
   * @minLength 0
   * @maxLength 255
   */
  connectionName: string;
  connectionType: CreateConnectionRequestConnectionType;
}

export interface CreateEmailTemplateRequest {
  /**
   * @minLength 0
   * @maxLength 100
   */
  appId: string;
  /** @minLength 1 */
  content: string;
  /**
   * @minLength 0
   * @maxLength 100
   */
  createdBy?: string;
  status: boolean;
  /**
   * @minLength 0
   * @maxLength 100
   */
  templateCode: string;
  /**
   * @minLength 0
   * @maxLength 50
   */
  templateType: string;
  /**
   * @minLength 0
   * @maxLength 255
   */
  title: string;
}

export type ExecuteServiceResponseServiceType = typeof ExecuteServiceResponseServiceType[keyof typeof ExecuteServiceResponseServiceType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExecuteServiceResponseServiceType = {
  REST: 'REST',
  DB: 'DB',
  PIPELINE: 'PIPELINE',
  EMAIL: 'EMAIL',
} as const;

export type ExecuteServiceResponseResponseHeaders = {[key: string]: string[]};

export interface JsonNode {}

export interface ExecuteServiceResponse {
  appId?: string;
  body?: JsonNode;
  responseHeaders?: ExecuteServiceResponseResponseHeaders;
  serviceCode?: string;
  serviceId?: number;
  serviceType?: ExecuteServiceResponseServiceType;
  serviceVersion?: string;
  statusCode?: number;
}

export type ExecuteServiceRequestHeaders = {[key: string]: string};

export interface ExecuteServiceRequest {
  headers?: ExecuteServiceRequestHeaders;
  payload?: JsonNode;
}

export interface CreateJobExecutionRequest {
  jobId: number;
  requestData?: string;
  startTime?: string;
}

export interface CreatePipelineStepRequest {
  continueOnError?: boolean;
  pipelineId: number;
  requestTransform?: string;
  responseTransform?: string;
  serviceId: number;
  /**
   * @minLength 0
   * @maxLength 255
   */
  stepName?: string;
  stepOrder: number;
}

export interface CreatePipelineRequest {
  active?: boolean;
  description?: string;
  /**
   * @minLength 0
   * @maxLength 100
   */
  pipelineCode: string;
  /**
   * @minLength 0
   * @maxLength 255
   */
  pipelineName: string;
}

export type CreateScheduleJobRequestJobType = typeof CreateScheduleJobRequestJobType[keyof typeof CreateScheduleJobRequestJobType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateScheduleJobRequestJobType = {
  SERVICE: 'SERVICE',
  PIPELINE: 'PIPELINE',
} as const;

export interface CreateScheduleJobRequest {
  /**
   * @minLength 0
   * @maxLength 50
   */
  cronExpression?: string;
  enabled?: boolean;
  fixedRateMs?: number;
  /**
   * @minLength 0
   * @maxLength 100
   */
  jobCode: string;
  /**
   * @minLength 0
   * @maxLength 255
   */
  jobName: string;
  jobType: CreateScheduleJobRequestJobType;
  pipelineId?: number;
  serviceId?: number;
}

export type CreateServiceRequestServiceType = typeof CreateServiceRequestServiceType[keyof typeof CreateServiceRequestServiceType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateServiceRequestServiceType = {
  REST: 'REST',
  DB: 'DB',
  PIPELINE: 'PIPELINE',
  EMAIL: 'EMAIL',
} as const;

export type CreateServiceRequestConfig = {[key: string]: unknown};

export interface CreateServiceRequest {
  active?: boolean;
  /**
   * @minLength 0
   * @maxLength 100
   */
  appId?: string;
  config?: CreateServiceRequestConfig;
  connectionId?: number;
  /**
   * @minLength 0
   * @maxLength 100
   */
  createdBy?: string;
  logEnable?: boolean;
  retryCount?: number;
  /**
   * @minLength 0
   * @maxLength 100
   */
  serviceCode: string;
  /**
   * @minLength 0
   * @maxLength 255
   */
  serviceName?: string;
  serviceType: CreateServiceRequestServiceType;
  /**
   * @minLength 0
   * @maxLength 50
   */
  serviceVersion?: string;
  timeoutMs?: number;
}

export type ConnectionResultConnectionType = typeof ConnectionResultConnectionType[keyof typeof ConnectionResultConnectionType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ConnectionResultConnectionType = {
  DB: 'DB',
  REST: 'REST',
  SOAP: 'SOAP',
  SFTP: 'SFTP',
  SMTP: 'SMTP',
  KAFKA: 'KAFKA',
} as const;

export interface ConnectionConfig {}

export interface ConnectionResult {
  active?: boolean;
  config?: ConnectionConfig;
  configJson?: string;
  connectionCode?: string;
  connectionName?: string;
  connectionType?: ConnectionResultConnectionType;
  createdAt?: string;
  id?: number;
  updatedAt?: string;
}

export type UpdateConnectionRequestConnectionType = typeof UpdateConnectionRequestConnectionType[keyof typeof UpdateConnectionRequestConnectionType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateConnectionRequestConnectionType = {
  DB: 'DB',
  REST: 'REST',
  SOAP: 'SOAP',
  SFTP: 'SFTP',
  SMTP: 'SMTP',
  KAFKA: 'KAFKA',
} as const;

export type UpdateConnectionRequestConfig = {[key: string]: unknown};

export interface UpdateConnectionRequest {
  active?: boolean;
  config?: UpdateConnectionRequestConfig;
  connectionName?: string;
  connectionType?: UpdateConnectionRequestConnectionType;
}

export interface EmailTemplateResult {
  appId?: string;
  content?: string;
  createdAt?: string;
  createdBy?: string;
  id?: number;
  status?: boolean;
  templateCode?: string;
  templateType?: string;
  title?: string;
  updatedAt?: string;
  updatedBy?: string;
}

export interface UpdateEmailTemplateRequest {
  content?: string;
  status?: boolean;
  /**
   * @minLength 0
   * @maxLength 50
   */
  templateType?: string;
  /**
   * @minLength 0
   * @maxLength 255
   */
  title?: string;
  /**
   * @minLength 0
   * @maxLength 100
   */
  updatedBy?: string;
}

export interface JobExecutionResult {
  createdAt?: string;
  endTime?: string;
  errorMessage?: string;
  id?: number;
  jobId?: number;
  requestData?: string;
  responseData?: string;
  startTime?: string;
  status?: string;
}

export interface UpdateJobExecutionRequest {
  endTime?: string;
  errorMessage?: string;
  responseData?: string;
  /**
   * @minLength 0
   * @maxLength 50
   */
  status?: string;
}

export interface PipelineStepResult {
  continueOnError?: boolean;
  createdAt?: string;
  id?: number;
  pipelineId?: number;
  requestTransform?: string;
  responseTransform?: string;
  serviceId?: number;
  stepName?: string;
  stepOrder?: number;
}

export interface UpdatePipelineStepRequest {
  continueOnError?: boolean;
  requestTransform?: string;
  responseTransform?: string;
  serviceId?: number;
  /**
   * @minLength 0
   * @maxLength 255
   */
  stepName?: string;
  stepOrder?: number;
}

export interface PipelineResult {
  active?: boolean;
  createdAt?: string;
  description?: string;
  id?: number;
  pipelineCode?: string;
  pipelineName?: string;
}

export interface UpdatePipelineRequest {
  active?: boolean;
  description?: string;
  /**
   * @minLength 0
   * @maxLength 255
   */
  pipelineName?: string;
}

export type ScheduleJobResultJobType = typeof ScheduleJobResultJobType[keyof typeof ScheduleJobResultJobType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ScheduleJobResultJobType = {
  SERVICE: 'SERVICE',
  PIPELINE: 'PIPELINE',
} as const;

export interface ScheduleJobResult {
  createdAt?: string;
  cronExpression?: string;
  enabled?: boolean;
  fixedRateMs?: number;
  id?: number;
  jobCode?: string;
  jobName?: string;
  jobType?: ScheduleJobResultJobType;
  lastRunTime?: string;
  nextRunTime?: string;
  pipelineId?: number;
  serviceId?: number;
}

export type UpdateScheduleJobRequestJobType = typeof UpdateScheduleJobRequestJobType[keyof typeof UpdateScheduleJobRequestJobType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateScheduleJobRequestJobType = {
  SERVICE: 'SERVICE',
  PIPELINE: 'PIPELINE',
} as const;

export interface UpdateScheduleJobRequest {
  /**
   * @minLength 0
   * @maxLength 50
   */
  cronExpression?: string;
  enabled?: boolean;
  fixedRateMs?: number;
  /**
   * @minLength 0
   * @maxLength 255
   */
  jobName?: string;
  jobType?: UpdateScheduleJobRequestJobType;
  pipelineId?: number;
  serviceId?: number;
}

export type ServiceResultServiceType = typeof ServiceResultServiceType[keyof typeof ServiceResultServiceType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ServiceResultServiceType = {
  REST: 'REST',
  DB: 'DB',
  PIPELINE: 'PIPELINE',
  EMAIL: 'EMAIL',
} as const;

export interface ServiceConfig {}

export interface ServiceResult {
  active?: boolean;
  appId?: string;
  config?: ServiceConfig;
  configJson?: string;
  connectionId?: number;
  createdAt?: string;
  createdBy?: string;
  id?: number;
  logEnable?: boolean;
  retryCount?: number;
  serviceCode?: string;
  serviceName?: string;
  serviceType?: ServiceResultServiceType;
  serviceVersion?: string;
  timeoutMs?: number;
  updatedAt?: string;
  updatedBy?: string;
}

export type UpdateServiceRequestServiceType = typeof UpdateServiceRequestServiceType[keyof typeof UpdateServiceRequestServiceType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateServiceRequestServiceType = {
  REST: 'REST',
  DB: 'DB',
  PIPELINE: 'PIPELINE',
  EMAIL: 'EMAIL',
} as const;

export type UpdateServiceRequestConfig = {[key: string]: unknown};

export interface UpdateServiceRequest {
  active?: boolean;
  /**
   * @minLength 0
   * @maxLength 100
   */
  appId?: string;
  config?: UpdateServiceRequestConfig;
  connectionId?: number;
  logEnable?: boolean;
  retryCount?: number;
  /**
   * @minLength 0
   * @maxLength 255
   */
  serviceName?: string;
  serviceType?: UpdateServiceRequestServiceType;
  /**
   * @minLength 0
   * @maxLength 50
   */
  serviceVersion?: string;
  timeoutMs?: number;
  /**
   * @minLength 0
   * @maxLength 100
   */
  updatedBy?: string;
}





  export const getEConnectorAPI = () => {
/**
 * @summary Get a service definition by id
 */
const findById = <TData = AxiosResponse<ServiceResult>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/service-definitions/${id}`,options
    );
  }

/**
 * @summary Update a service definition
 */
const update = <TData = AxiosResponse<ServiceResult>>(
    id: number,
    updateServiceRequest: UpdateServiceRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/service-definitions/${id}`,
      updateServiceRequest,options
    );
  }

/**
 * @summary Delete a service definition
 */
const _delete = <TData = AxiosResponse<void>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/service-definitions/${id}`,options
    );
  }

/**
 * @summary Get a scheduled job by id
 */
const findById1 = <TData = AxiosResponse<ScheduleJobResult>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/schedule-jobs/${id}`,options
    );
  }

/**
 * @summary Update a scheduled job
 */
const update1 = <TData = AxiosResponse<ScheduleJobResult>>(
    id: number,
    updateScheduleJobRequest: UpdateScheduleJobRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/schedule-jobs/${id}`,
      updateScheduleJobRequest,options
    );
  }

/**
 * @summary Delete a scheduled job
 */
const delete1 = <TData = AxiosResponse<void>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/schedule-jobs/${id}`,options
    );
  }

/**
 * @summary Get a pipeline by id
 */
const findById2 = <TData = AxiosResponse<PipelineResult>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/pipelines/${id}`,options
    );
  }

/**
 * @summary Update a pipeline
 */
const update2 = <TData = AxiosResponse<PipelineResult>>(
    id: number,
    updatePipelineRequest: UpdatePipelineRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/pipelines/${id}`,
      updatePipelineRequest,options
    );
  }

/**
 * @summary Delete a pipeline
 */
const delete2 = <TData = AxiosResponse<void>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/pipelines/${id}`,options
    );
  }

/**
 * @summary Get a pipeline step by id
 */
const findById3 = <TData = AxiosResponse<PipelineStepResult>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/pipeline-steps/${id}`,options
    );
  }

/**
 * @summary Update a pipeline step
 */
const update3 = <TData = AxiosResponse<PipelineStepResult>>(
    id: number,
    updatePipelineStepRequest: UpdatePipelineStepRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/pipeline-steps/${id}`,
      updatePipelineStepRequest,options
    );
  }

/**
 * @summary Delete a pipeline step
 */
const delete3 = <TData = AxiosResponse<void>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/pipeline-steps/${id}`,options
    );
  }

/**
 * @summary Get a job execution by id
 */
const findById4 = <TData = AxiosResponse<JobExecutionResult>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/job-executions/${id}`,options
    );
  }

/**
 * @summary Update a job execution
 */
const update4 = <TData = AxiosResponse<JobExecutionResult>>(
    id: number,
    updateJobExecutionRequest: UpdateJobExecutionRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/job-executions/${id}`,
      updateJobExecutionRequest,options
    );
  }

/**
 * @summary Delete a job execution
 */
const delete4 = <TData = AxiosResponse<void>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/job-executions/${id}`,options
    );
  }

/**
 * @summary Get an email template by id
 */
const findById5 = <TData = AxiosResponse<EmailTemplateResult>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/email-templates/${id}`,options
    );
  }

/**
 * @summary Update an email template
 */
const update5 = <TData = AxiosResponse<EmailTemplateResult>>(
    id: number,
    updateEmailTemplateRequest: UpdateEmailTemplateRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/email-templates/${id}`,
      updateEmailTemplateRequest,options
    );
  }

/**
 * @summary Delete an email template
 */
const delete5 = <TData = AxiosResponse<void>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/email-templates/${id}`,options
    );
  }

/**
 * @summary Get a connection definition by id
 */
const findById6 = <TData = AxiosResponse<ConnectionResult>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/connection-definitions/${id}`,options
    );
  }

/**
 * @summary Update a connection definition
 */
const update6 = <TData = AxiosResponse<ConnectionResult>>(
    id: number,
    updateConnectionRequest: UpdateConnectionRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/connection-definitions/${id}`,
      updateConnectionRequest,options
    );
  }

/**
 * @summary Delete a connection definition
 */
const delete6 = <TData = AxiosResponse<void>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/connection-definitions/${id}`,options
    );
  }

/**
 * @summary List service definitions
 */
const findAll = <TData = AxiosResponse<PageServiceResult>>(
    params?: FindAllParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/service-definitions`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Create a service definition
 */
const create = <TData = AxiosResponse<ServiceResult>>(
    createServiceRequest: CreateServiceRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/service-definitions`,
      createServiceRequest,options
    );
  }

/**
 * @summary List scheduled jobs
 */
const findAll1 = <TData = AxiosResponse<PageScheduleJobResult>>(
    params?: FindAll1Params, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/schedule-jobs`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Create a scheduled job
 */
const create1 = <TData = AxiosResponse<ScheduleJobResult>>(
    createScheduleJobRequest: CreateScheduleJobRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/schedule-jobs`,
      createScheduleJobRequest,options
    );
  }

/**
 * @summary List pipelines
 */
const findAll2 = <TData = AxiosResponse<PagePipelineResult>>(
    params?: FindAll2Params, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/pipelines`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Create a pipeline
 */
const create2 = <TData = AxiosResponse<PipelineResult>>(
    createPipelineRequest: CreatePipelineRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/pipelines`,
      createPipelineRequest,options
    );
  }

/**
 * @summary List pipeline steps
 */
const findAll3 = <TData = AxiosResponse<PagePipelineStepResult>>(
    params?: FindAll3Params, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/pipeline-steps`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Create a pipeline step
 */
const create3 = <TData = AxiosResponse<PipelineStepResult>>(
    createPipelineStepRequest: CreatePipelineStepRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/pipeline-steps`,
      createPipelineStepRequest,options
    );
  }

/**
 * @summary List job executions
 */
const findAll4 = <TData = AxiosResponse<PageJobExecutionResult>>(
    params?: FindAll4Params, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/job-executions`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Create a job execution
 */
const create4 = <TData = AxiosResponse<JobExecutionResult>>(
    createJobExecutionRequest: CreateJobExecutionRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/job-executions`,
      createJobExecutionRequest,options
    );
  }

/**
 * @summary Execute a service
 */
const execute = <TData = AxiosResponse<ExecuteServiceResponse>>(
    appId: string,
    serviceCode: string,
    serviceVersion: string,
    executeServiceRequest: ExecuteServiceRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/execute/${appId}/${serviceCode}/${serviceVersion}`,
      executeServiceRequest,options
    );
  }

/**
 * @summary List email templates
 */
const findAll5 = <TData = AxiosResponse<PageEmailTemplateResult>>(
    params?: FindAll5Params, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/email-templates`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Create an email template
 */
const create5 = <TData = AxiosResponse<EmailTemplateResult>>(
    createEmailTemplateRequest: CreateEmailTemplateRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/email-templates`,
      createEmailTemplateRequest,options
    );
  }

/**
 * @summary List connection definitions
 */
const findAll6 = <TData = AxiosResponse<PageConnectionResult>>(
    params?: FindAll6Params, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/connection-definitions`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Create a connection definition
 */
const create6 = <TData = AxiosResponse<ConnectionResult>>(
    createConnectionRequest: CreateConnectionRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/connection-definitions`,
      createConnectionRequest,options
    );
  }

/**
 * @summary Get a service definition schema
 */
const getSchema = <TData = AxiosResponse<GetSchema200>>(
    serviceType: 'REST' | 'DB' | 'PIPELINE' | 'EMAIL', options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/service-definition-schemas/${serviceType}`,options
    );
  }

/**
 * @summary List logs
 */
const findAll7 = <TData = AxiosResponse<PageLogResult>>(
    params?: FindAll7Params, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/logs`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Get a log entry
 */
const findById7 = <TData = AxiosResponse<LogResult>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/logs/${id}`,options
    );
  }

/**
 * @summary List all enum options
 */
const findAll8 = <TData = AxiosResponse<FindAll8200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/enums`,options
    );
  }

/**
 * @summary List options for a single enum
 */
const findByName = <TData = AxiosResponse<EnumOptionResponse[]>>(
    enumName: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/enums/${enumName}`,options
    );
  }

/**
 * @summary Get a connection configuration schema
 */
const getSchema1 = <TData = AxiosResponse<GetSchema1200>>(
    connectionType: 'DB' | 'REST' | 'SOAP' | 'SFTP' | 'SMTP' | 'KAFKA', options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/connection-definition-schemas/${connectionType}`,options
    );
  }

return {findById,update,_delete,findById1,update1,delete1,findById2,update2,delete2,findById3,update3,delete3,findById4,update4,delete4,findById5,update5,delete5,findById6,update6,delete6,findAll,create,findAll1,create1,findAll2,create2,findAll3,create3,findAll4,create4,execute,findAll5,create5,findAll6,create6,getSchema,findAll7,findById7,findAll8,findByName,getSchema1}};
export type FindByIdResult = AxiosResponse<ServiceResult>
export type UpdateResult = AxiosResponse<ServiceResult>
export type _DeleteResult = AxiosResponse<void>
export type FindById1Result = AxiosResponse<ScheduleJobResult>
export type Update1Result = AxiosResponse<ScheduleJobResult>
export type Delete1Result = AxiosResponse<void>
export type FindById2Result = AxiosResponse<PipelineResult>
export type Update2Result = AxiosResponse<PipelineResult>
export type Delete2Result = AxiosResponse<void>
export type FindById3Result = AxiosResponse<PipelineStepResult>
export type Update3Result = AxiosResponse<PipelineStepResult>
export type Delete3Result = AxiosResponse<void>
export type FindById4Result = AxiosResponse<JobExecutionResult>
export type Update4Result = AxiosResponse<JobExecutionResult>
export type Delete4Result = AxiosResponse<void>
export type FindById5Result = AxiosResponse<EmailTemplateResult>
export type Update5Result = AxiosResponse<EmailTemplateResult>
export type Delete5Result = AxiosResponse<void>
export type FindById6Result = AxiosResponse<ConnectionResult>
export type Update6Result = AxiosResponse<ConnectionResult>
export type Delete6Result = AxiosResponse<void>
export type FindAllResult = AxiosResponse<PageServiceResult>
export type CreateResult = AxiosResponse<ServiceResult>
export type FindAll1Result = AxiosResponse<PageScheduleJobResult>
export type Create1Result = AxiosResponse<ScheduleJobResult>
export type FindAll2Result = AxiosResponse<PagePipelineResult>
export type Create2Result = AxiosResponse<PipelineResult>
export type FindAll3Result = AxiosResponse<PagePipelineStepResult>
export type Create3Result = AxiosResponse<PipelineStepResult>
export type FindAll4Result = AxiosResponse<PageJobExecutionResult>
export type Create4Result = AxiosResponse<JobExecutionResult>
export type ExecuteResult = AxiosResponse<ExecuteServiceResponse>
export type FindAll5Result = AxiosResponse<PageEmailTemplateResult>
export type Create5Result = AxiosResponse<EmailTemplateResult>
export type FindAll6Result = AxiosResponse<PageConnectionResult>
export type Create6Result = AxiosResponse<ConnectionResult>
export type GetSchemaResult = AxiosResponse<GetSchema200>
export type FindAll7Result = AxiosResponse<PageLogResult>
export type FindById7Result = AxiosResponse<LogResult>
export type FindAll8Result = AxiosResponse<FindAll8200>
export type FindByNameResult = AxiosResponse<EnumOptionResponse[]>
export type GetSchema1Result = AxiosResponse<GetSchema1200>
