/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export type UserUpdateRequestStatus = typeof UserUpdateRequestStatus[keyof typeof UserUpdateRequestStatus];


export const UserUpdateRequestStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  LOCKED: 'LOCKED',
  SUSPENDED: 'SUSPENDED',
} as const;

export type UserUpdateRequestSource = typeof UserUpdateRequestSource[keyof typeof UserUpdateRequestSource];


export const UserUpdateRequestSource = {
  LOCAL: 'LOCAL',
  KEYCLOAK: 'KEYCLOAK',
  LDAP: 'LDAP',
  AD: 'AD',
} as const;

export interface UserUpdateRequest {
  externalId?: string;
  username?: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  fullName?: string;
  phoneNumber?: string;
  status?: UserUpdateRequestStatus;
  source?: UserUpdateRequestSource;
}

export type UserResponseStatus = typeof UserResponseStatus[keyof typeof UserResponseStatus];


export const UserResponseStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  LOCKED: 'LOCKED',
  SUSPENDED: 'SUSPENDED',
} as const;

export type UserResponseSource = typeof UserResponseSource[keyof typeof UserResponseSource];


export const UserResponseSource = {
  LOCAL: 'LOCAL',
  KEYCLOAK: 'KEYCLOAK',
  LDAP: 'LDAP',
  AD: 'AD',
} as const;

export interface UserResponse {
  id?: number;
  externalId?: string;
  username?: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  fullName?: string;
  phoneNumber?: string;
  status?: UserResponseStatus;
  source?: UserResponseSource;
  deleted?: boolean;
  createdAt?: string;
  updatedAt?: string;
}

export type RoleUpdateRequestRoleType = typeof RoleUpdateRequestRoleType[keyof typeof RoleUpdateRequestRoleType];


export const RoleUpdateRequestRoleType = {
  SYSTEM: 'SYSTEM',
  BUSINESS: 'BUSINESS',
  CAMUNDA: 'CAMUNDA',
  APPROVAL: 'APPROVAL',
} as const;

export type RoleUpdateRequestSource = typeof RoleUpdateRequestSource[keyof typeof RoleUpdateRequestSource];


export const RoleUpdateRequestSource = {
  LOCAL: 'LOCAL',
  KEYCLOAK: 'KEYCLOAK',
  LDAP: 'LDAP',
  AD: 'AD',
} as const;

export interface RoleUpdateRequest {
  code?: string;
  name?: string;
  roleType?: RoleUpdateRequestRoleType;
  description?: string;
  source?: RoleUpdateRequestSource;
  system?: boolean;
}

export type RoleResponseRoleType = typeof RoleResponseRoleType[keyof typeof RoleResponseRoleType];


export const RoleResponseRoleType = {
  SYSTEM: 'SYSTEM',
  BUSINESS: 'BUSINESS',
  CAMUNDA: 'CAMUNDA',
  APPROVAL: 'APPROVAL',
} as const;

export type RoleResponseSource = typeof RoleResponseSource[keyof typeof RoleResponseSource];


export const RoleResponseSource = {
  LOCAL: 'LOCAL',
  KEYCLOAK: 'KEYCLOAK',
  LDAP: 'LDAP',
  AD: 'AD',
} as const;

export interface RoleResponse {
  id?: number;
  code?: string;
  name?: string;
  roleType?: RoleResponseRoleType;
  description?: string;
  source?: RoleResponseSource;
  system?: boolean;
  createdAt?: string;
}

export type IdentityProviderUpdateRequestConfig = {[key: string]: unknown};

export interface IdentityProviderUpdateRequest {
  providerCode?: string;
  providerName?: string;
  providerType?: string;
  config?: IdentityProviderUpdateRequestConfig;
  active?: boolean;
}

export type IdentityProviderResponseConfig = {[key: string]: unknown};

export interface IdentityProviderResponse {
  id?: number;
  providerCode?: string;
  providerName?: string;
  providerType?: string;
  config?: IdentityProviderResponseConfig;
  active?: boolean;
  createdAt?: string;
}

export type GroupUpdateRequestGroupType = typeof GroupUpdateRequestGroupType[keyof typeof GroupUpdateRequestGroupType];


export const GroupUpdateRequestGroupType = {
  DEPARTMENT: 'DEPARTMENT',
  TEAM: 'TEAM',
  PROJECT: 'PROJECT',
  SECURITY: 'SECURITY',
  CAMUNDA: 'CAMUNDA',
} as const;

export type GroupUpdateRequestSource = typeof GroupUpdateRequestSource[keyof typeof GroupUpdateRequestSource];


export const GroupUpdateRequestSource = {
  LOCAL: 'LOCAL',
  KEYCLOAK: 'KEYCLOAK',
  LDAP: 'LDAP',
  AD: 'AD',
} as const;

export interface GroupUpdateRequest {
  code?: string;
  name?: string;
  parentGroupId?: number;
  groupType?: GroupUpdateRequestGroupType;
  path?: string;
  description?: string;
  source?: GroupUpdateRequestSource;
}

export type GroupResponseGroupType = typeof GroupResponseGroupType[keyof typeof GroupResponseGroupType];


export const GroupResponseGroupType = {
  DEPARTMENT: 'DEPARTMENT',
  TEAM: 'TEAM',
  PROJECT: 'PROJECT',
  SECURITY: 'SECURITY',
  CAMUNDA: 'CAMUNDA',
} as const;

export type GroupResponseSource = typeof GroupResponseSource[keyof typeof GroupResponseSource];


export const GroupResponseSource = {
  LOCAL: 'LOCAL',
  KEYCLOAK: 'KEYCLOAK',
  LDAP: 'LDAP',
  AD: 'AD',
} as const;

export interface GroupResponse {
  id?: number;
  code?: string;
  name?: string;
  parentGroupId?: number;
  groupType?: GroupResponseGroupType;
  path?: string;
  description?: string;
  source?: GroupResponseSource;
  active?: boolean;
  createdAt?: string;
}

export type UserCreateRequestStatus = typeof UserCreateRequestStatus[keyof typeof UserCreateRequestStatus];


export const UserCreateRequestStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  LOCKED: 'LOCKED',
  SUSPENDED: 'SUSPENDED',
} as const;

export type UserCreateRequestSource = typeof UserCreateRequestSource[keyof typeof UserCreateRequestSource];


export const UserCreateRequestSource = {
  LOCAL: 'LOCAL',
  KEYCLOAK: 'KEYCLOAK',
  LDAP: 'LDAP',
  AD: 'AD',
} as const;

export interface UserCreateRequest {
  externalId?: string;
  /** @minLength 1 */
  username: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  fullName?: string;
  phoneNumber?: string;
  status: UserCreateRequestStatus;
  source: UserCreateRequestSource;
}

export interface AssignUserRoleRequest {
  userId: number;
  roleId: number;
  expiresAt?: string;
}

export interface UserRoleResponse {
  userId?: number;
  roleId?: number;
  assignedAt?: string;
  expiresAt?: string;
}

export interface AddUserGroupRequest {
  userId: number;
  groupId: number;
}

export interface UserGroupResponse {
  userId?: number;
  groupId?: number;
  joinedAt?: string;
}

export type RoleCreateRequestRoleType = typeof RoleCreateRequestRoleType[keyof typeof RoleCreateRequestRoleType];


export const RoleCreateRequestRoleType = {
  SYSTEM: 'SYSTEM',
  BUSINESS: 'BUSINESS',
  CAMUNDA: 'CAMUNDA',
  APPROVAL: 'APPROVAL',
} as const;

export type RoleCreateRequestSource = typeof RoleCreateRequestSource[keyof typeof RoleCreateRequestSource];


export const RoleCreateRequestSource = {
  LOCAL: 'LOCAL',
  KEYCLOAK: 'KEYCLOAK',
  LDAP: 'LDAP',
  AD: 'AD',
} as const;

export interface RoleCreateRequest {
  /** @minLength 1 */
  code: string;
  /** @minLength 1 */
  name: string;
  roleType: RoleCreateRequestRoleType;
  description?: string;
  source: RoleCreateRequestSource;
  system?: boolean;
}

export interface GrantRolePermissionRequest {
  roleId: number;
  permissionId: number;
}

export interface RolePermissionResponse {
  roleId?: number;
  permissionId?: number;
}

export type IdentityProviderCreateRequestConfig = {[key: string]: unknown};

export interface IdentityProviderCreateRequest {
  /** @minLength 1 */
  providerCode: string;
  /** @minLength 1 */
  providerName: string;
  /** @minLength 1 */
  providerType: string;
  config: IdentityProviderCreateRequestConfig;
  active?: boolean;
}

export type GroupCreateRequestGroupType = typeof GroupCreateRequestGroupType[keyof typeof GroupCreateRequestGroupType];


export const GroupCreateRequestGroupType = {
  DEPARTMENT: 'DEPARTMENT',
  TEAM: 'TEAM',
  PROJECT: 'PROJECT',
  SECURITY: 'SECURITY',
  CAMUNDA: 'CAMUNDA',
} as const;

export type GroupCreateRequestSource = typeof GroupCreateRequestSource[keyof typeof GroupCreateRequestSource];


export const GroupCreateRequestSource = {
  LOCAL: 'LOCAL',
  KEYCLOAK: 'KEYCLOAK',
  LDAP: 'LDAP',
  AD: 'AD',
} as const;

export interface GroupCreateRequest {
  /** @minLength 1 */
  code: string;
  /** @minLength 1 */
  name: string;
  parentGroupId?: number;
  groupType: GroupCreateRequestGroupType;
  path?: string;
  description?: string;
  source: GroupCreateRequestSource;
}

export const getOpenAPIDefinition = (axiosInstance: AxiosInstance = axios.default) => {
/**
 * Returns a single user by identifier
 * @summary Get a user by ID
 */
const findById = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserResponse>> => {
    return axiosInstance.get(
      `/api/users/${id}`,options
    );
  }

/**
 * Updates an existing user record
 * @summary Update a user
 */
const update = (
    id: number,
    userUpdateRequest: UserUpdateRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserResponse>> => {
    return axiosInstance.put(
      `/api/users/${id}`,
      userUpdateRequest,options
    );
  }

/**
 * Marks a user as inactive and deleted
 * @summary Deactivate a user
 */
const deactivate = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserResponse>> => {
    return axiosInstance.put(
      `/api/users/${id}/deactivate`,
      undefined,options
    );
  }

/**
 * Returns a single role by identifier
 * @summary Get a role by ID
 */
const findById1 = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<RoleResponse>> => {
    return axiosInstance.get(
      `/api/roles/${id}`,options
    );
  }

/**
 * Updates an existing role record
 * @summary Update a role
 */
const update1 = (
    id: number,
    roleUpdateRequest: RoleUpdateRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<RoleResponse>> => {
    return axiosInstance.put(
      `/api/roles/${id}`,
      roleUpdateRequest,options
    );
  }

/**
 * Returns a single identity provider by identifier
 * @summary Get an identity provider by ID
 */
const findById2 = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<IdentityProviderResponse>> => {
    return axiosInstance.get(
      `/api/identity-providers/${id}`,options
    );
  }

/**
 * Updates an existing identity provider record
 * @summary Update an identity provider
 */
const update2 = (
    id: number,
    identityProviderUpdateRequest: IdentityProviderUpdateRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<IdentityProviderResponse>> => {
    return axiosInstance.put(
      `/api/identity-providers/${id}`,
      identityProviderUpdateRequest,options
    );
  }

/**
 * Returns a single group by identifier
 * @summary Get a group by ID
 */
const findById3 = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GroupResponse>> => {
    return axiosInstance.get(
      `/api/groups/${id}`,options
    );
  }

/**
 * Updates an existing group record
 * @summary Update a group
 */
const update3 = (
    id: number,
    groupUpdateRequest: GroupUpdateRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GroupResponse>> => {
    return axiosInstance.put(
      `/api/groups/${id}`,
      groupUpdateRequest,options
    );
  }

/**
 * Returns all users
 * @summary List users
 */
const findAll = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserResponse[]>> => {
    return axiosInstance.get(
      `/api/users`,options
    );
  }

/**
 * Creates a new user record
 * @summary Create a user
 */
const create = (
    userCreateRequest: UserCreateRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserResponse>> => {
    return axiosInstance.post(
      `/api/users`,
      userCreateRequest,options
    );
  }

/**
 * Creates a user-role assignment
 * @summary Assign a role to a user
 */
const assign = (
    assignUserRoleRequest: AssignUserRoleRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserRoleResponse>> => {
    return axiosInstance.post(
      `/api/user-roles`,
      assignUserRoleRequest,options
    );
  }

/**
 * Creates a user-group membership
 * @summary Add a user to a group
 */
const add = (
    addUserGroupRequest: AddUserGroupRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserGroupResponse>> => {
    return axiosInstance.post(
      `/api/user-groups`,
      addUserGroupRequest,options
    );
  }

/**
 * Returns all roles
 * @summary List roles
 */
const findAll1 = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<RoleResponse[]>> => {
    return axiosInstance.get(
      `/api/roles`,options
    );
  }

/**
 * Creates a new role record
 * @summary Create a role
 */
const create1 = (
    roleCreateRequest: RoleCreateRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<RoleResponse>> => {
    return axiosInstance.post(
      `/api/roles`,
      roleCreateRequest,options
    );
  }

/**
 * Creates a role-permission grant
 * @summary Grant a permission to a role
 */
const grant = (
    grantRolePermissionRequest: GrantRolePermissionRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<RolePermissionResponse>> => {
    return axiosInstance.post(
      `/api/role-permissions`,
      grantRolePermissionRequest,options
    );
  }

/**
 * Returns all identity providers
 * @summary List identity providers
 */
const findAll2 = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<IdentityProviderResponse[]>> => {
    return axiosInstance.get(
      `/api/identity-providers`,options
    );
  }

/**
 * Creates a new identity provider record
 * @summary Create an identity provider
 */
const create2 = (
    identityProviderCreateRequest: IdentityProviderCreateRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<IdentityProviderResponse>> => {
    return axiosInstance.post(
      `/api/identity-providers`,
      identityProviderCreateRequest,options
    );
  }

/**
 * Returns all groups
 * @summary List groups
 */
const findAll3 = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GroupResponse[]>> => {
    return axiosInstance.get(
      `/api/groups`,options
    );
  }

/**
 * Creates a new group record
 * @summary Create a group
 */
const create3 = (
    groupCreateRequest: GroupCreateRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GroupResponse>> => {
    return axiosInstance.post(
      `/api/groups`,
      groupCreateRequest,options
    );
  }

/**
 * Returns a single user by username
 * @summary Get a user by username
 */
const findByUsername = (
    username: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserResponse>> => {
    return axiosInstance.get(
      `/api/users/username/${username}`,options
    );
  }

/**
 * Returns a single user by external identifier
 * @summary Get a user by external ID
 */
const findByExternalId = (
    externalId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserResponse>> => {
    return axiosInstance.get(
      `/api/users/external/${externalId}`,options
    );
  }

/**
 * Returns a single assignment by user and role
 * @summary Get a user-role assignment
 */
const find = (
    userId: number,
    roleId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserRoleResponse>> => {
    return axiosInstance.get(
      `/api/user-roles/${userId}/${roleId}`,options
    );
  }

/**
 * Deletes a user-role assignment
 * @summary Revoke a user role
 */
const revoke = (
    userId: number,
    roleId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/api/user-roles/${userId}/${roleId}`,options
    );
  }

/**
 * Returns all role assignments for the given user
 * @summary List roles for a user
 */
const findByUserId = (
    userId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserRoleResponse[]>> => {
    return axiosInstance.get(
      `/api/user-roles/user/${userId}`,options
    );
  }

/**
 * Returns a single membership by user and group
 * @summary Get a user-group membership
 */
const find1 = (
    userId: number,
    groupId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserGroupResponse>> => {
    return axiosInstance.get(
      `/api/user-groups/${userId}/${groupId}`,options
    );
  }

/**
 * Deletes a user-group membership
 * @summary Remove a user from a group
 */
const remove = (
    userId: number,
    groupId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/api/user-groups/${userId}/${groupId}`,options
    );
  }

/**
 * Returns all group memberships for the given user
 * @summary List groups for a user
 */
const findByUserId1 = (
    userId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserGroupResponse[]>> => {
    return axiosInstance.get(
      `/api/user-groups/user/${userId}`,options
    );
  }

/**
 * Returns a single role by code
 * @summary Get a role by code
 */
const findByCode = (
    code: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<RoleResponse>> => {
    return axiosInstance.get(
      `/api/roles/code/${code}`,options
    );
  }

/**
 * Returns a single grant by role and permission
 * @summary Get a role-permission grant
 */
const find2 = (
    roleId: number,
    permissionId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<RolePermissionResponse>> => {
    return axiosInstance.get(
      `/api/role-permissions/${roleId}/${permissionId}`,options
    );
  }

/**
 * Deletes a role-permission grant
 * @summary Revoke a role permission
 */
const revoke1 = (
    roleId: number,
    permissionId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/api/role-permissions/${roleId}/${permissionId}`,options
    );
  }

/**
 * Returns all permission grants for the given role
 * @summary List permissions for a role
 */
const findByRoleId = (
    roleId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<RolePermissionResponse[]>> => {
    return axiosInstance.get(
      `/api/role-permissions/role/${roleId}`,options
    );
  }

/**
 * Returns a single identity provider by provider code
 * @summary Get an identity provider by code
 */
const findByProviderCode = (
    providerCode: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<IdentityProviderResponse>> => {
    return axiosInstance.get(
      `/api/identity-providers/code/${providerCode}`,options
    );
  }

/**
 * Returns a single group by code
 * @summary Get a group by code
 */
const findByCode1 = (
    code: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GroupResponse>> => {
    return axiosInstance.get(
      `/api/groups/code/${code}`,options
    );
  }

return {findById,update,deactivate,findById1,update1,findById2,update2,findById3,update3,findAll,create,assign,add,findAll1,create1,grant,findAll2,create2,findAll3,create3,findByUsername,findByExternalId,find,revoke,findByUserId,find1,remove,findByUserId1,findByCode,find2,revoke1,findByRoleId,findByProviderCode,findByCode1}};
export type FindByIdResult = AxiosResponse<UserResponse>
export type UpdateResult = AxiosResponse<UserResponse>
export type DeactivateResult = AxiosResponse<UserResponse>
export type FindById1Result = AxiosResponse<RoleResponse>
export type Update1Result = AxiosResponse<RoleResponse>
export type FindById2Result = AxiosResponse<IdentityProviderResponse>
export type Update2Result = AxiosResponse<IdentityProviderResponse>
export type FindById3Result = AxiosResponse<GroupResponse>
export type Update3Result = AxiosResponse<GroupResponse>
export type FindAllResult = AxiosResponse<UserResponse[]>
export type CreateResult = AxiosResponse<UserResponse>
export type AssignResult = AxiosResponse<UserRoleResponse>
export type AddResult = AxiosResponse<UserGroupResponse>
export type FindAll1Result = AxiosResponse<RoleResponse[]>
export type Create1Result = AxiosResponse<RoleResponse>
export type GrantResult = AxiosResponse<RolePermissionResponse>
export type FindAll2Result = AxiosResponse<IdentityProviderResponse[]>
export type Create2Result = AxiosResponse<IdentityProviderResponse>
export type FindAll3Result = AxiosResponse<GroupResponse[]>
export type Create3Result = AxiosResponse<GroupResponse>
export type FindByUsernameResult = AxiosResponse<UserResponse>
export type FindByExternalIdResult = AxiosResponse<UserResponse>
export type FindResult = AxiosResponse<UserRoleResponse>
export type RevokeResult = AxiosResponse<void>
export type FindByUserIdResult = AxiosResponse<UserRoleResponse[]>
export type Find1Result = AxiosResponse<UserGroupResponse>
export type RemoveResult = AxiosResponse<void>
export type FindByUserId1Result = AxiosResponse<UserGroupResponse[]>
export type FindByCodeResult = AxiosResponse<RoleResponse>
export type Find2Result = AxiosResponse<RolePermissionResponse>
export type Revoke1Result = AxiosResponse<void>
export type FindByRoleIdResult = AxiosResponse<RolePermissionResponse[]>
export type FindByProviderCodeResult = AxiosResponse<IdentityProviderResponse>
export type FindByCode1Result = AxiosResponse<GroupResponse>
