server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location /e-connector/ {
    alias /usr/share/nginx/html/;
    try_files $uri $uri/ /e-connector/index.html;
  }

  location = /e-connector {
    return 301 /e-connector/;
  }

  location = / {
    return 301 /e-connector/;
  }
}
