/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import findByIdMutator from '../../lib/orvalMutator';
import updateMutator from '../../lib/orvalMutator';
import deactivateMutator from '../../lib/orvalMutator';
import findById1Mutator from '../../lib/orvalMutator';
import update1Mutator from '../../lib/orvalMutator';
import findById2Mutator from '../../lib/orvalMutator';
import update2Mutator from '../../lib/orvalMutator';
import findById3Mutator from '../../lib/orvalMutator';
import update3Mutator from '../../lib/orvalMutator';
import findAllMutator from '../../lib/orvalMutator';
import createMutator from '../../lib/orvalMutator';
import assignMutator from '../../lib/orvalMutator';
import addMutator from '../../lib/orvalMutator';
import findAll1Mutator from '../../lib/orvalMutator';
import create1Mutator from '../../lib/orvalMutator';
import grantMutator from '../../lib/orvalMutator';
import findAll2Mutator from '../../lib/orvalMutator';
import create2Mutator from '../../lib/orvalMutator';
import findAll3Mutator from '../../lib/orvalMutator';
import create3Mutator from '../../lib/orvalMutator';
import findByUsernameMutator from '../../lib/orvalMutator';
import findByExternalIdMutator from '../../lib/orvalMutator';
import findMutator from '../../lib/orvalMutator';
import revokeMutator from '../../lib/orvalMutator';
import findByUserIdMutator from '../../lib/orvalMutator';
import find1Mutator from '../../lib/orvalMutator';
import removeMutator from '../../lib/orvalMutator';
import findByUserId1Mutator from '../../lib/orvalMutator';
import findByCodeMutator from '../../lib/orvalMutator';
import find2Mutator from '../../lib/orvalMutator';
import revoke1Mutator from '../../lib/orvalMutator';
import findByRoleIdMutator from '../../lib/orvalMutator';
import findByProviderCodeMutator from '../../lib/orvalMutator';
import findByCode1Mutator from '../../lib/orvalMutator';
export type UserUpdateRequestStatus = typeof UserUpdateRequestStatus[keyof typeof UserUpdateRequestStatus];


export const UserUpdateRequestStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  LOCKED: 'LOCKED',
  SUSPENDED: 'SUSPENDED',
} as const;

export type UserUpdateRequestSource = typeof UserUpdateRequestSource[keyof typeof UserUpdateRequestSource];


export const UserUpdateRequestSource = {
  LOCAL: 'LOCAL',
  KEYCLOAK: 'KEYCLOAK',
  LDAP: 'LDAP',
  AD: 'AD',
} as const;

export interface UserUpdateRequest {
  externalId?: string;
  username?: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  fullName?: string;
  phoneNumber?: string;
  status?: UserUpdateRequestStatus;
  source?: UserUpdateRequestSource;
}

export type UserResponseStatus = typeof UserResponseStatus[keyof typeof UserResponseStatus];


export const UserResponseStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  LOCKED: 'LOCKED',
  SUSPENDED: 'SUSPENDED',
} as const;

export type UserResponseSource = typeof UserResponseSource[keyof typeof UserResponseSource];


export const UserResponseSource = {
  LOCAL: 'LOCAL',
  KEYCLOAK: 'KEYCLOAK',
  LDAP: 'LDAP',
  AD: 'AD',
} as const;

export interface UserResponse {
  id?: number;
  externalId?: string;
  username?: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  fullName?: string;
  phoneNumber?: string;
  status?: UserResponseStatus;
  source?: UserResponseSource;
  deleted?: boolean;
  createdAt?: string;
  updatedAt?: string;
}

export type RoleUpdateRequestRoleType = typeof RoleUpdateRequestRoleType[keyof typeof RoleUpdateRequestRoleType];


export const RoleUpdateRequestRoleType = {
  SYSTEM: 'SYSTEM',
  BUSINESS: 'BUSINESS',
  CAMUNDA: 'CAMUNDA',
  APPROVAL: 'APPROVAL',
} as const;

export type RoleUpdateRequestSource = typeof RoleUpdateRequestSource[keyof typeof RoleUpdateRequestSource];


export const RoleUpdateRequestSource = {
  LOCAL: 'LOCAL',
  KEYCLOAK: 'KEYCLOAK',
  LDAP: 'LDAP',
  AD: 'AD',
} as const;

export interface RoleUpdateRequest {
  code?: string;
  name?: string;
  roleType?: RoleUpdateRequestRoleType;
  description?: string;
  source?: RoleUpdateRequestSource;
  system?: boolean;
}

export type RoleResponseRoleType = typeof RoleResponseRoleType[keyof typeof RoleResponseRoleType];


export const RoleResponseRoleType = {
  SYSTEM: 'SYSTEM',
  BUSINESS: 'BUSINESS',
  CAMUNDA: 'CAMUNDA',
  APPROVAL: 'APPROVAL',
} as const;

export type RoleResponseSource = typeof RoleResponseSource[keyof typeof RoleResponseSource];


export const RoleResponseSource = {
  LOCAL: 'LOCAL',
  KEYCLOAK: 'KEYCLOAK',
  LDAP: 'LDAP',
  AD: 'AD',
} as const;

export interface RoleResponse {
  id?: number;
  code?: string;
  name?: string;
  roleType?: RoleResponseRoleType;
  description?: string;
  source?: RoleResponseSource;
  system?: boolean;
  createdAt?: string;
}

export type IdentityProviderUpdateRequestConfig = {[key: string]: unknown};

export interface IdentityProviderUpdateRequest {
  providerCode?: string;
  providerName?: string;
  providerType?: string;
  config?: IdentityProviderUpdateRequestConfig;
  active?: boolean;
}

export type IdentityProviderResponseConfig = {[key: string]: unknown};

export interface IdentityProviderResponse {
  id?: number;
  providerCode?: string;
  providerName?: string;
  providerType?: string;
  config?: IdentityProviderResponseConfig;
  active?: boolean;
  createdAt?: string;
}

export type GroupUpdateRequestGroupType = typeof GroupUpdateRequestGroupType[keyof typeof GroupUpdateRequestGroupType];


export const GroupUpdateRequestGroupType = {
  DEPARTMENT: 'DEPARTMENT',
  TEAM: 'TEAM',
  PROJECT: 'PROJECT',
  SECURITY: 'SECURITY',
  CAMUNDA: 'CAMUNDA',
} as const;

export type GroupUpdateRequestSource = typeof GroupUpdateRequestSource[keyof typeof GroupUpdateRequestSource];


export const GroupUpdateRequestSource = {
  LOCAL: 'LOCAL',
  KEYCLOAK: 'KEYCLOAK',
  LDAP: 'LDAP',
  AD: 'AD',
} as const;

export interface GroupUpdateRequest {
  code?: string;
  name?: string;
  parentGroupId?: number;
  groupType?: GroupUpdateRequestGroupType;
  path?: string;
  description?: string;
  source?: GroupUpdateRequestSource;
}

export type GroupResponseGroupType = typeof GroupResponseGroupType[keyof typeof GroupResponseGroupType];


export const GroupResponseGroupType = {
  DEPARTMENT: 'DEPARTMENT',
  TEAM: 'TEAM',
  PROJECT: 'PROJECT',
  SECURITY: 'SECURITY',
  CAMUNDA: 'CAMUNDA',
} as const;

export type GroupResponseSource = typeof GroupResponseSource[keyof typeof GroupResponseSource];


export const GroupResponseSource = {
  LOCAL: 'LOCAL',
  KEYCLOAK: 'KEYCLOAK',
  LDAP: 'LDAP',
  AD: 'AD',
} as const;

export interface GroupResponse {
  id?: number;
  code?: string;
  name?: string;
  parentGroupId?: number;
  groupType?: GroupResponseGroupType;
  path?: string;
  description?: string;
  source?: GroupResponseSource;
  active?: boolean;
  createdAt?: string;
}

export type UserCreateRequestStatus = typeof UserCreateRequestStatus[keyof typeof UserCreateRequestStatus];


export const UserCreateRequestStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  LOCKED: 'LOCKED',
  SUSPENDED: 'SUSPENDED',
} as const;

export type UserCreateRequestSource = typeof UserCreateRequestSource[keyof typeof UserCreateRequestSource];


export const UserCreateRequestSource = {
  LOCAL: 'LOCAL',
  KEYCLOAK: 'KEYCLOAK',
  LDAP: 'LDAP',
  AD: 'AD',
} as const;

export interface UserCreateRequest {
  externalId?: string;
  /** @minLength 1 */
  username: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  fullName?: string;
  phoneNumber?: string;
  status: UserCreateRequestStatus;
  source: UserCreateRequestSource;
}

export interface AssignUserRoleRequest {
  userId: number;
  roleId: number;
  expiresAt?: string;
}

export interface UserRoleResponse {
  userId?: number;
  roleId?: number;
  assignedAt?: string;
  expiresAt?: string;
}

export interface AddUserGroupRequest {
  userId: number;
  groupId: number;
}

export interface UserGroupResponse {
  userId?: number;
  groupId?: number;
  joinedAt?: string;
}

export type RoleCreateRequestRoleType = typeof RoleCreateRequestRoleType[keyof typeof RoleCreateRequestRoleType];


export const RoleCreateRequestRoleType = {
  SYSTEM: 'SYSTEM',
  BUSINESS: 'BUSINESS',
  CAMUNDA: 'CAMUNDA',
  APPROVAL: 'APPROVAL',
} as const;

export type RoleCreateRequestSource = typeof RoleCreateRequestSource[keyof typeof RoleCreateRequestSource];


export const RoleCreateRequestSource = {
  LOCAL: 'LOCAL',
  KEYCLOAK: 'KEYCLOAK',
  LDAP: 'LDAP',
  AD: 'AD',
} as const;

export interface RoleCreateRequest {
  /** @minLength 1 */
  code: string;
  /** @minLength 1 */
  name: string;
  roleType: RoleCreateRequestRoleType;
  description?: string;
  source: RoleCreateRequestSource;
  system?: boolean;
}

export interface GrantRolePermissionRequest {
  roleId: number;
  permissionId: number;
}

export interface RolePermissionResponse {
  roleId?: number;
  permissionId?: number;
}

export type IdentityProviderCreateRequestConfig = {[key: string]: unknown};

export interface IdentityProviderCreateRequest {
  /** @minLength 1 */
  providerCode: string;
  /** @minLength 1 */
  providerName: string;
  /** @minLength 1 */
  providerType: string;
  config: IdentityProviderCreateRequestConfig;
  active?: boolean;
}

export type GroupCreateRequestGroupType = typeof GroupCreateRequestGroupType[keyof typeof GroupCreateRequestGroupType];


export const GroupCreateRequestGroupType = {
  DEPARTMENT: 'DEPARTMENT',
  TEAM: 'TEAM',
  PROJECT: 'PROJECT',
  SECURITY: 'SECURITY',
  CAMUNDA: 'CAMUNDA',
} as const;

export type GroupCreateRequestSource = typeof GroupCreateRequestSource[keyof typeof GroupCreateRequestSource];


export const GroupCreateRequestSource = {
  LOCAL: 'LOCAL',
  KEYCLOAK: 'KEYCLOAK',
  LDAP: 'LDAP',
  AD: 'AD',
} as const;

export interface GroupCreateRequest {
  /** @minLength 1 */
  code: string;
  /** @minLength 1 */
  name: string;
  parentGroupId?: number;
  groupType: GroupCreateRequestGroupType;
  path?: string;
  description?: string;
  source: GroupCreateRequestSource;
}

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getOpenAPIDefinition = () => {
/**
 * Returns a single user by identifier
 * @summary Get a user by ID
 */
const findById = (
    id: number,
 options?: SecondParameter<typeof findByIdMutator<UserResponse>>,) => {
      return findByIdMutator<UserResponse>(
      {url: `/api/users/${id}`, method: 'GET'
    },
      options);
    }

/**
 * Updates an existing user record
 * @summary Update a user
 */
const update = (
    id: number,
    userUpdateRequest: UserUpdateRequest,
 options?: SecondParameter<typeof updateMutator<UserResponse>>,) => {
      return updateMutator<UserResponse>(
      {url: `/api/users/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: userUpdateRequest
    },
      options);
    }

/**
 * Marks a user as inactive and deleted
 * @summary Deactivate a user
 */
const deactivate = (
    id: number,
 options?: SecondParameter<typeof deactivateMutator<UserResponse>>,) => {
      return deactivateMutator<UserResponse>(
      {url: `/api/users/${id}/deactivate`, method: 'PUT'
    },
      options);
    }

/**
 * Returns a single role by identifier
 * @summary Get a role by ID
 */
const findById1 = (
    id: number,
 options?: SecondParameter<typeof findById1Mutator<RoleResponse>>,) => {
      return findById1Mutator<RoleResponse>(
      {url: `/api/roles/${id}`, method: 'GET'
    },
      options);
    }

/**
 * Updates an existing role record
 * @summary Update a role
 */
const update1 = (
    id: number,
    roleUpdateRequest: RoleUpdateRequest,
 options?: SecondParameter<typeof update1Mutator<RoleResponse>>,) => {
      return update1Mutator<RoleResponse>(
      {url: `/api/roles/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: roleUpdateRequest
    },
      options);
    }

/**
 * Returns a single identity provider by identifier
 * @summary Get an identity provider by ID
 */
const findById2 = (
    id: number,
 options?: SecondParameter<typeof findById2Mutator<IdentityProviderResponse>>,) => {
      return findById2Mutator<IdentityProviderResponse>(
      {url: `/api/identity-providers/${id}`, method: 'GET'
    },
      options);
    }

/**
 * Updates an existing identity provider record
 * @summary Update an identity provider
 */
const update2 = (
    id: number,
    identityProviderUpdateRequest: IdentityProviderUpdateRequest,
 options?: SecondParameter<typeof update2Mutator<IdentityProviderResponse>>,) => {
      return update2Mutator<IdentityProviderResponse>(
      {url: `/api/identity-providers/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: identityProviderUpdateRequest
    },
      options);
    }

/**
 * Returns a single group by identifier
 * @summary Get a group by ID
 */
const findById3 = (
    id: number,
 options?: SecondParameter<typeof findById3Mutator<GroupResponse>>,) => {
      return findById3Mutator<GroupResponse>(
      {url: `/api/groups/${id}`, method: 'GET'
    },
      options);
    }

/**
 * Updates an existing group record
 * @summary Update a group
 */
const update3 = (
    id: number,
    groupUpdateRequest: GroupUpdateRequest,
 options?: SecondParameter<typeof update3Mutator<GroupResponse>>,) => {
      return update3Mutator<GroupResponse>(
      {url: `/api/groups/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: groupUpdateRequest
    },
      options);
    }

/**
 * Returns all users
 * @summary List users
 */
const findAll = (

 options?: SecondParameter<typeof findAllMutator<UserResponse[]>>,) => {
      return findAllMutator<UserResponse[]>(
      {url: `/api/users`, method: 'GET'
    },
      options);
    }

/**
 * Creates a new user record
 * @summary Create a user
 */
const create = (
    userCreateRequest: UserCreateRequest,
 options?: SecondParameter<typeof createMutator<UserResponse>>,) => {
      return createMutator<UserResponse>(
      {url: `/api/users`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userCreateRequest
    },
      options);
    }

/**
 * Creates a user-role assignment
 * @summary Assign a role to a user
 */
const assign = (
    assignUserRoleRequest: AssignUserRoleRequest,
 options?: SecondParameter<typeof assignMutator<UserRoleResponse>>,) => {
      return assignMutator<UserRoleResponse>(
      {url: `/api/user-roles`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: assignUserRoleRequest
    },
      options);
    }

/**
 * Creates a user-group membership
 * @summary Add a user to a group
 */
const add = (
    addUserGroupRequest: AddUserGroupRequest,
 options?: SecondParameter<typeof addMutator<UserGroupResponse>>,) => {
      return addMutator<UserGroupResponse>(
      {url: `/api/user-groups`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addUserGroupRequest
    },
      options);
    }

/**
 * Returns all roles
 * @summary List roles
 */
const findAll1 = (

 options?: SecondParameter<typeof findAll1Mutator<RoleResponse[]>>,) => {
      return findAll1Mutator<RoleResponse[]>(
      {url: `/api/roles`, method: 'GET'
    },
      options);
    }

/**
 * Creates a new role record
 * @summary Create a role
 */
const create1 = (
    roleCreateRequest: RoleCreateRequest,
 options?: SecondParameter<typeof create1Mutator<RoleResponse>>,) => {
      return create1Mutator<RoleResponse>(
      {url: `/api/roles`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: roleCreateRequest
    },
      options);
    }

/**
 * Creates a role-permission grant
 * @summary Grant a permission to a role
 */
const grant = (
    grantRolePermissionRequest: GrantRolePermissionRequest,
 options?: SecondParameter<typeof grantMutator<RolePermissionResponse>>,) => {
      return grantMutator<RolePermissionResponse>(
      {url: `/api/role-permissions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: grantRolePermissionRequest
    },
      options);
    }

/**
 * Returns all identity providers
 * @summary List identity providers
 */
const findAll2 = (

 options?: SecondParameter<typeof findAll2Mutator<IdentityProviderResponse[]>>,) => {
      return findAll2Mutator<IdentityProviderResponse[]>(
      {url: `/api/identity-providers`, method: 'GET'
    },
      options);
    }

/**
 * Creates a new identity provider record
 * @summary Create an identity provider
 */
const create2 = (
    identityProviderCreateRequest: IdentityProviderCreateRequest,
 options?: SecondParameter<typeof create2Mutator<IdentityProviderResponse>>,) => {
      return create2Mutator<IdentityProviderResponse>(
      {url: `/api/identity-providers`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: identityProviderCreateRequest
    },
      options);
    }

/**
 * Returns all groups
 * @summary List groups
 */
const findAll3 = (

 options?: SecondParameter<typeof findAll3Mutator<GroupResponse[]>>,) => {
      return findAll3Mutator<GroupResponse[]>(
      {url: `/api/groups`, method: 'GET'
    },
      options);
    }

/**
 * Creates a new group record
 * @summary Create a group
 */
const create3 = (
    groupCreateRequest: GroupCreateRequest,
 options?: SecondParameter<typeof create3Mutator<GroupResponse>>,) => {
      return create3Mutator<GroupResponse>(
      {url: `/api/groups`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: groupCreateRequest
    },
      options);
    }

/**
 * Returns a single user by username
 * @summary Get a user by username
 */
const findByUsername = (
    username: string,
 options?: SecondParameter<typeof findByUsernameMutator<UserResponse>>,) => {
      return findByUsernameMutator<UserResponse>(
      {url: `/api/users/username/${username}`, method: 'GET'
    },
      options);
    }

/**
 * Returns a single user by external identifier
 * @summary Get a user by external ID
 */
const findByExternalId = (
    externalId: string,
 options?: SecondParameter<typeof findByExternalIdMutator<UserResponse>>,) => {
      return findByExternalIdMutator<UserResponse>(
      {url: `/api/users/external/${externalId}`, method: 'GET'
    },
      options);
    }

/**
 * Returns a single assignment by user and role
 * @summary Get a user-role assignment
 */
const find = (
    userId: number,
    roleId: number,
 options?: SecondParameter<typeof findMutator<UserRoleResponse>>,) => {
      return findMutator<UserRoleResponse>(
      {url: `/api/user-roles/${userId}/${roleId}`, method: 'GET'
    },
      options);
    }

/**
 * Deletes a user-role assignment
 * @summary Revoke a user role
 */
const revoke = (
    userId: number,
    roleId: number,
 options?: SecondParameter<typeof revokeMutator<void>>,) => {
      return revokeMutator<void>(
      {url: `/api/user-roles/${userId}/${roleId}`, method: 'DELETE'
    },
      options);
    }

/**
 * Returns all role assignments for the given user
 * @summary List roles for a user
 */
const findByUserId = (
    userId: number,
 options?: SecondParameter<typeof findByUserIdMutator<UserRoleResponse[]>>,) => {
      return findByUserIdMutator<UserRoleResponse[]>(
      {url: `/api/user-roles/user/${userId}`, method: 'GET'
    },
      options);
    }

/**
 * Returns a single membership by user and group
 * @summary Get a user-group membership
 */
const find1 = (
    userId: number,
    groupId: number,
 options?: SecondParameter<typeof find1Mutator<UserGroupResponse>>,) => {
      return find1Mutator<UserGroupResponse>(
      {url: `/api/user-groups/${userId}/${groupId}`, method: 'GET'
    },
      options);
    }

/**
 * Deletes a user-group membership
 * @summary Remove a user from a group
 */
const remove = (
    userId: number,
    groupId: number,
 options?: SecondParameter<typeof removeMutator<void>>,) => {
      return removeMutator<void>(
      {url: `/api/user-groups/${userId}/${groupId}`, method: 'DELETE'
    },
      options);
    }

/**
 * Returns all group memberships for the given user
 * @summary List groups for a user
 */
const findByUserId1 = (
    userId: number,
 options?: SecondParameter<typeof findByUserId1Mutator<UserGroupResponse[]>>,) => {
      return findByUserId1Mutator<UserGroupResponse[]>(
      {url: `/api/user-groups/user/${userId}`, method: 'GET'
    },
      options);
    }

/**
 * Returns a single role by code
 * @summary Get a role by code
 */
const findByCode = (
    code: string,
 options?: SecondParameter<typeof findByCodeMutator<RoleResponse>>,) => {
      return findByCodeMutator<RoleResponse>(
      {url: `/api/roles/code/${code}`, method: 'GET'
    },
      options);
    }

/**
 * Returns a single grant by role and permission
 * @summary Get a role-permission grant
 */
const find2 = (
    roleId: number,
    permissionId: number,
 options?: SecondParameter<typeof find2Mutator<RolePermissionResponse>>,) => {
      return find2Mutator<RolePermissionResponse>(
      {url: `/api/role-permissions/${roleId}/${permissionId}`, method: 'GET'
    },
      options);
    }

/**
 * Deletes a role-permission grant
 * @summary Revoke a role permission
 */
const revoke1 = (
    roleId: number,
    permissionId: number,
 options?: SecondParameter<typeof revoke1Mutator<void>>,) => {
      return revoke1Mutator<void>(
      {url: `/api/role-permissions/${roleId}/${permissionId}`, method: 'DELETE'
    },
      options);
    }

/**
 * Returns all permission grants for the given role
 * @summary List permissions for a role
 */
const findByRoleId = (
    roleId: number,
 options?: SecondParameter<typeof findByRoleIdMutator<RolePermissionResponse[]>>,) => {
      return findByRoleIdMutator<RolePermissionResponse[]>(
      {url: `/api/role-permissions/role/${roleId}`, method: 'GET'
    },
      options);
    }

/**
 * Returns a single identity provider by provider code
 * @summary Get an identity provider by code
 */
const findByProviderCode = (
    providerCode: string,
 options?: SecondParameter<typeof findByProviderCodeMutator<IdentityProviderResponse>>,) => {
      return findByProviderCodeMutator<IdentityProviderResponse>(
      {url: `/api/identity-providers/code/${providerCode}`, method: 'GET'
    },
      options);
    }

/**
 * Returns a single group by code
 * @summary Get a group by code
 */
const findByCode1 = (
    code: string,
 options?: SecondParameter<typeof findByCode1Mutator<GroupResponse>>,) => {
      return findByCode1Mutator<GroupResponse>(
      {url: `/api/groups/code/${code}`, method: 'GET'
    },
      options);
    }

return {findById,update,deactivate,findById1,update1,findById2,update2,findById3,update3,findAll,create,assign,add,findAll1,create1,grant,findAll2,create2,findAll3,create3,findByUsername,findByExternalId,find,revoke,findByUserId,find1,remove,findByUserId1,findByCode,find2,revoke1,findByRoleId,findByProviderCode,findByCode1}};
export type FindByIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenAPIDefinition>['findById']>>>
export type UpdateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenAPIDefinition>['update']>>>
export type DeactivateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenAPIDefinition>['deactivate']>>>
export type FindById1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenAPIDefinition>['findById1']>>>
export type Update1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenAPIDefinition>['update1']>>>
export type FindById2Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenAPIDefinition>['findById2']>>>
export type Update2Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenAPIDefinition>['update2']>>>
export type FindById3Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenAPIDefinition>['findById3']>>>
export type Update3Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenAPIDefinition>['update3']>>>
export type FindAllResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenAPIDefinition>['findAll']>>>
export type CreateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenAPIDefinition>['create']>>>
export type AssignResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenAPIDefinition>['assign']>>>
export type AddResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenAPIDefinition>['add']>>>
export type FindAll1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenAPIDefinition>['findAll1']>>>
export type Create1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenAPIDefinition>['create1']>>>
export type GrantResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenAPIDefinition>['grant']>>>
export type FindAll2Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenAPIDefinition>['findAll2']>>>
export type Create2Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenAPIDefinition>['create2']>>>
export type FindAll3Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenAPIDefinition>['findAll3']>>>
export type Create3Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenAPIDefinition>['create3']>>>
export type FindByUsernameResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenAPIDefinition>['findByUsername']>>>
export type FindByExternalIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenAPIDefinition>['findByExternalId']>>>
export type FindResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenAPIDefinition>['find']>>>
export type RevokeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenAPIDefinition>['revoke']>>>
export type FindByUserIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenAPIDefinition>['findByUserId']>>>
export type Find1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenAPIDefinition>['find1']>>>
export type RemoveResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenAPIDefinition>['remove']>>>
export type FindByUserId1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenAPIDefinition>['findByUserId1']>>>
export type FindByCodeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenAPIDefinition>['findByCode']>>>
export type Find2Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenAPIDefinition>['find2']>>>
export type Revoke1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenAPIDefinition>['revoke1']>>>
export type FindByRoleIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenAPIDefinition>['findByRoleId']>>>
export type FindByProviderCodeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenAPIDefinition>['findByProviderCode']>>>
export type FindByCode1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenAPIDefinition>['findByCode1']>>>
