spring.application.name=connector-service

server.port=${SERVER_PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/connector}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true
spring.flyway.clean-disabled=true
logging.level.org.flywaydb=INFO
logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG

spring.quartz.job-store-type=memory

spring.cloud.config.enabled=false

# Eureka client
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=${EUREKA_INSTANCE_PREFER_IP_ADDRESS:true}
eureka.instance.instance-id=${spring.application.name}:${server.port}

# Swagger config
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
# springdoc.swagger-ui.enabled=false # for production
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operationsSorter=alpha

# ===============================
# CRYPTO CONFIG
# ===============================
app.crypto.key=${APP_CRYPTO_KEY:1234567890123456}

# ===============================
# MAIL CONFIG
# ===============================

mail.host=${MAIL_HOST:smtp.gmail.com}
mail.port=${MAIL_PORT:587}
mail.username=${MAIL_USERNAME}
mail.password=${MAIL_PASSWORD}

# optional (if using JavaMailSender later)
mail.smtp.auth=true
mail.smtp.starttls.enable=true
