/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * E-Document API
 * API documentation for the E-Document service
 * OpenAPI spec version: v1
 */
import * as axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface CreateFileRequest {
  fileName?: string;
  contentType?: string;
  categoryCode?: string;
}

export interface FileResult {
  id?: number;
  fileName?: string;
  contentType?: string;
  size?: number;
  createdAt?: string;
}

export interface FileAttributeValueRequest {
  key?: string;
  value?: unknown;
}

export interface FileAttributeValuesRequest {
  attributes?: FileAttributeValueRequest[];
}

export interface UpdateFileCategoryRequest {
  name?: string;
  maxSize?: number;
  bucketName?: string;
  retentionDays?: number;
  isPublic?: boolean;
}

export interface FileCategoryResult {
  id?: number;
  code?: string;
  name?: string;
  isPublic?: boolean;
}

export interface PresignedUploadRequest {
  fileName?: string;
  contentType?: string;
  categoryCode?: string;
}

export interface PresignedUploadResult {
  uploadUrl?: string;
  objectKey?: string;
  bucket?: string;
}

export interface PresignedPartRequest {
  bucket?: string;
  objectKey?: string;
  uploadId?: string;
  partNumber?: number;
}

export interface PresignedPartResult {
  url?: string;
}

export interface InitiateMultipartRequest {
  categoryCode?: string;
  fileName?: string;
}

export interface InitiateMultipartResult {
  uploadId?: string;
  objectKey?: string;
  bucket?: string;
}

export interface PartETag {
  partNumber?: number;
  etag?: string;
}

export interface CompleteMultipartRequest {
  objectKey?: string;
  uploadId?: string;
  parts?: PartETag[];
  fileName?: string;
  categoryCode?: string;
  contentType?: string;
  size?: number;
}

export interface CompleteUploadRequest {
  objectKey?: string;
  fileName?: string;
  size?: number;
  contentType?: string;
  categoryCode?: string;
}

export interface CreateFileCategoryRequest {
  code?: string;
  name?: string;
  maxSize?: number;
  bucketName?: string;
  retentionDays?: number;
  isPublic?: boolean;
}

export interface AddContentTypeRequest {
  contentType?: string;
}

export type CreateFileAttributeRequestDataType = typeof CreateFileAttributeRequestDataType[keyof typeof CreateFileAttributeRequestDataType];


export const CreateFileAttributeRequestDataType = {
  STRING: 'STRING',
  NUMBER: 'NUMBER',
  DATE: 'DATE',
  BOOLEAN: 'BOOLEAN',
  LIST: 'LIST',
} as const;

export interface CreateFileAttributeRequest {
  keyCode?: string;
  displayName?: string;
  dataType?: CreateFileAttributeRequestDataType;
  isRequired?: boolean;
}

export type FileAttributeResultDataType = typeof FileAttributeResultDataType[keyof typeof FileAttributeResultDataType];


export const FileAttributeResultDataType = {
  STRING: 'STRING',
  NUMBER: 'NUMBER',
  DATE: 'DATE',
  BOOLEAN: 'BOOLEAN',
  LIST: 'LIST',
} as const;

export interface FileAttributeResult {
  id?: number;
  keyCode?: string;
  displayName?: string;
  dataType?: FileAttributeResultDataType;
  isRequired?: boolean;
}

export interface AddOptionRequest {
  optionLabel?: string;
  optionValue?: string;
  sortOrder?: number;
}

export interface Pageable {
  /** @minimum 0 */
  page?: number;
  /** @minimum 1 */
  size?: number;
  sort?: string[];
}

export interface SortObject {
  sorted?: boolean;
  empty?: boolean;
  unsorted?: boolean;
}

export interface PageableObject {
  paged?: boolean;
  pageNumber?: number;
  pageSize?: number;
  offset?: number;
  sort?: SortObject;
  unpaged?: boolean;
}

export interface PageFileResult {
  totalElements?: number;
  totalPages?: number;
  pageable?: PageableObject;
  last?: boolean;
  first?: boolean;
  size?: number;
  content?: FileResult[];
  number?: number;
  sort?: SortObject;
  numberOfElements?: number;
  empty?: boolean;
}

export type ListParams = {
pageable: Pageable;
};

export const getEDocumentAPI = (axiosInstance: AxiosInstance = axios.default) => {
const get = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<FileResult>> => {
    return axiosInstance.get(
      `/api/v1/files/${id}`,options
    );
  }

const update = (
    id: number,
    createFileRequest: CreateFileRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<FileResult>> => {
    return axiosInstance.put(
      `/api/v1/files/${id}`,
      createFileRequest,options
    );
  }

const _delete = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/api/v1/files/${id}`,options
    );
  }

const update1 = (
    fileId: number,
    fileAttributeValuesRequest?: FileAttributeValuesRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.put(
      `/api/v1/files/${fileId}/attributes`,
      fileAttributeValuesRequest,options
    );
  }

const create = (
    fileId: number,
    fileAttributeValuesRequest?: FileAttributeValuesRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/v1/files/${fileId}/attributes`,
      fileAttributeValuesRequest,options
    );
  }

const update2 = (
    id: number,
    updateFileCategoryRequest?: UpdateFileCategoryRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<FileCategoryResult>> => {
    return axiosInstance.put(
      `/api/v1/file-categories/${id}`,
      updateFileCategoryRequest,options
    );
  }

const presignedUpload = (
    presignedUploadRequest: PresignedUploadRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PresignedUploadResult>> => {
    return axiosInstance.post(
      `/api/v1/files/presigned-upload`,
      presignedUploadRequest,options
    );
  }

const presignedPart = (
    presignedPartRequest: PresignedPartRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PresignedPartResult>> => {
    return axiosInstance.post(
      `/api/v1/files/multipart/presigned-part`,
      presignedPartRequest,options
    );
  }

const init = (
    initiateMultipartRequest: InitiateMultipartRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<InitiateMultipartResult>> => {
    return axiosInstance.post(
      `/api/v1/files/multipart/init`,
      initiateMultipartRequest,options
    );
  }

const complete = (
    completeMultipartRequest: CompleteMultipartRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<FileResult>> => {
    return axiosInstance.post(
      `/api/v1/files/multipart/complete`,
      completeMultipartRequest,options
    );
  }

const completeUpload = (
    completeUploadRequest: CompleteUploadRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<FileResult>> => {
    return axiosInstance.post(
      `/api/v1/files/complete-upload`,
      completeUploadRequest,options
    );
  }

const getAll = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<FileCategoryResult[]>> => {
    return axiosInstance.get(
      `/api/v1/file-categories`,options
    );
  }

const create1 = (
    createFileCategoryRequest?: CreateFileCategoryRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<FileCategoryResult>> => {
    return axiosInstance.post(
      `/api/v1/file-categories`,
      createFileCategoryRequest,options
    );
  }

const addContentType = (
    id: number,
    addContentTypeRequest?: AddContentTypeRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/v1/file-categories/${id}/content-types`,
      addContentTypeRequest,options
    );
  }

const getAll1 = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<FileAttributeResult[]>> => {
    return axiosInstance.get(
      `/api/v1/file-attributes`,options
    );
  }

const create2 = (
    createFileAttributeRequest?: CreateFileAttributeRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<FileAttributeResult>> => {
    return axiosInstance.post(
      `/api/v1/file-attributes`,
      createFileAttributeRequest,options
    );
  }

const addOption = (
    id: number,
    addOptionRequest?: AddOptionRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/v1/file-attributes/${id}/options`,
      addOptionRequest,options
    );
  }

const list = (
    params: ListParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PageFileResult>> => {
    return axiosInstance.get(
      `/api/v1/files`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const presignedDownload = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string>> => {
    return axiosInstance.get(
      `/api/v1/files/${id}/presigned-download`,{
    ...options,}
    );
  }

return {get,update,_delete,update1,create,update2,presignedUpload,presignedPart,init,complete,completeUpload,getAll,create1,addContentType,getAll1,create2,addOption,list,presignedDownload}};
export type GetResult = AxiosResponse<FileResult>
export type UpdateResult = AxiosResponse<FileResult>
export type _DeleteResult = AxiosResponse<void>
export type Update1Result = AxiosResponse<void>
export type CreateResult = AxiosResponse<void>
export type Update2Result = AxiosResponse<FileCategoryResult>
export type PresignedUploadResult = AxiosResponse<PresignedUploadResult>
export type PresignedPartResult = AxiosResponse<PresignedPartResult>
export type InitResult = AxiosResponse<InitiateMultipartResult>
export type CompleteResult = AxiosResponse<FileResult>
export type CompleteUploadResult = AxiosResponse<FileResult>
export type GetAllResult = AxiosResponse<FileCategoryResult[]>
export type Create1Result = AxiosResponse<FileCategoryResult>
export type AddContentTypeResult = AxiosResponse<void>
export type GetAll1Result = AxiosResponse<FileAttributeResult[]>
export type Create2Result = AxiosResponse<FileAttributeResult>
export type AddOptionResult = AxiosResponse<void>
export type ListResult = AxiosResponse<PageFileResult>
export type PresignedDownloadResult = AxiosResponse<string>
