/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * E-Document API
 * API documentation for the E-Document service
 * OpenAPI spec version: v1
 */
import { orvalMutator } from '../../lib/orvalMutatorDocument';
export interface CreateFileRequest {
  fileName?: string;
  contentType?: string;
  categoryCode?: string;
}

export interface FileResult {
  id?: number;
  fileName?: string;
  contentType?: string;
  size?: number;
  createdAt?: string;
}

export interface FileAttributeValueRequest {
  key?: string;
  value?: unknown;
}

export interface FileAttributeValuesRequest {
  attributes?: FileAttributeValueRequest[];
}

export interface UpdateFileCategoryRequest {
  name?: string;
  maxSize?: number;
  bucketName?: string;
  retentionDays?: number;
  isPublic?: boolean;
}

export interface FileCategoryResult {
  id?: number;
  code?: string;
  name?: string;
  isPublic?: boolean;
}

export interface PresignedUploadRequest {
  fileName?: string;
  contentType?: string;
  categoryCode?: string;
}

export interface PresignedUploadResult {
  uploadUrl?: string;
  objectKey?: string;
  bucket?: string;
}

export interface PresignedPartRequest {
  bucket?: string;
  objectKey?: string;
  uploadId?: string;
  partNumber?: number;
}

export interface PresignedPartResult {
  url?: string;
}

export interface InitiateMultipartRequest {
  categoryCode?: string;
  fileName?: string;
}

export interface InitiateMultipartResult {
  uploadId?: string;
  objectKey?: string;
  bucket?: string;
}

export interface PartETag {
  partNumber?: number;
  etag?: string;
}

export interface CompleteMultipartRequest {
  objectKey?: string;
  uploadId?: string;
  parts?: PartETag[];
  fileName?: string;
  categoryCode?: string;
  contentType?: string;
  size?: number;
}

export interface CompleteUploadRequest {
  objectKey?: string;
  fileName?: string;
  size?: number;
  contentType?: string;
  categoryCode?: string;
}

export interface CreateFileCategoryRequest {
  code?: string;
  name?: string;
  maxSize?: number;
  bucketName?: string;
  retentionDays?: number;
  isPublic?: boolean;
}

export interface AddContentTypeRequest {
  contentType?: string;
}

export type CreateFileAttributeRequestDataType = typeof CreateFileAttributeRequestDataType[keyof typeof CreateFileAttributeRequestDataType];


export const CreateFileAttributeRequestDataType = {
  STRING: 'STRING',
  NUMBER: 'NUMBER',
  DATE: 'DATE',
  BOOLEAN: 'BOOLEAN',
  LIST: 'LIST',
} as const;

export interface CreateFileAttributeRequest {
  keyCode?: string;
  displayName?: string;
  dataType?: CreateFileAttributeRequestDataType;
  isRequired?: boolean;
}

export type FileAttributeResultDataType = typeof FileAttributeResultDataType[keyof typeof FileAttributeResultDataType];


export const FileAttributeResultDataType = {
  STRING: 'STRING',
  NUMBER: 'NUMBER',
  DATE: 'DATE',
  BOOLEAN: 'BOOLEAN',
  LIST: 'LIST',
} as const;

export interface FileAttributeResult {
  id?: number;
  keyCode?: string;
  displayName?: string;
  dataType?: FileAttributeResultDataType;
  isRequired?: boolean;
}

export interface AddOptionRequest {
  optionLabel?: string;
  optionValue?: string;
  sortOrder?: number;
}

export interface Pageable {
  /** @minimum 0 */
  page?: number;
  /** @minimum 1 */
  size?: number;
  sort?: string[];
}

export interface SortObject {
  sorted?: boolean;
  empty?: boolean;
  unsorted?: boolean;
}

export interface PageableObject {
  paged?: boolean;
  pageNumber?: number;
  pageSize?: number;
  offset?: number;
  sort?: SortObject;
  unpaged?: boolean;
}

export interface PageFileResult {
  totalElements?: number;
  totalPages?: number;
  pageable?: PageableObject;
  last?: boolean;
  first?: boolean;
  size?: number;
  content?: FileResult[];
  number?: number;
  sort?: SortObject;
  numberOfElements?: number;
  empty?: boolean;
}

export type ListParams = {
pageable: Pageable;
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getEDocumentAPI = () => {
const get = (
    id: number,
 options?: SecondParameter<typeof orvalMutator<FileResult>>,) => {
      return orvalMutator<FileResult>(
      {url: `/api/v1/files/${id}`, method: 'GET'
    },
      options);
    }

const update = (
    id: number,
    createFileRequest: CreateFileRequest,
 options?: SecondParameter<typeof orvalMutator<FileResult>>,) => {
      return orvalMutator<FileResult>(
      {url: `/api/v1/files/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: createFileRequest
    },
      options);
    }

const _delete = (
    id: number,
 options?: SecondParameter<typeof orvalMutator<void>>,) => {
      return orvalMutator<void>(
      {url: `/api/v1/files/${id}`, method: 'DELETE'
    },
      options);
    }

const update1 = (
    fileId: number,
    fileAttributeValuesRequest?: FileAttributeValuesRequest,
 options?: SecondParameter<typeof orvalMutator<void>>,) => {
      return orvalMutator<void>(
      {url: `/api/v1/files/${fileId}/attributes`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: fileAttributeValuesRequest
    },
      options);
    }

const create = (
    fileId: number,
    fileAttributeValuesRequest?: FileAttributeValuesRequest,
 options?: SecondParameter<typeof orvalMutator<void>>,) => {
      return orvalMutator<void>(
      {url: `/api/v1/files/${fileId}/attributes`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: fileAttributeValuesRequest
    },
      options);
    }

const update2 = (
    id: number,
    updateFileCategoryRequest?: UpdateFileCategoryRequest,
 options?: SecondParameter<typeof orvalMutator<FileCategoryResult>>,) => {
      return orvalMutator<FileCategoryResult>(
      {url: `/api/v1/file-categories/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateFileCategoryRequest
    },
      options);
    }

const presignedUpload = (
    presignedUploadRequest: PresignedUploadRequest,
 options?: SecondParameter<typeof orvalMutator<PresignedUploadResult>>,) => {
      return orvalMutator<PresignedUploadResult>(
      {url: `/api/v1/files/presigned-upload`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: presignedUploadRequest
    },
      options);
    }

const presignedPart = (
    presignedPartRequest: PresignedPartRequest,
 options?: SecondParameter<typeof orvalMutator<PresignedPartResult>>,) => {
      return orvalMutator<PresignedPartResult>(
      {url: `/api/v1/files/multipart/presigned-part`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: presignedPartRequest
    },
      options);
    }

const init = (
    initiateMultipartRequest: InitiateMultipartRequest,
 options?: SecondParameter<typeof orvalMutator<InitiateMultipartResult>>,) => {
      return orvalMutator<InitiateMultipartResult>(
      {url: `/api/v1/files/multipart/init`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: initiateMultipartRequest
    },
      options);
    }

const complete = (
    completeMultipartRequest: CompleteMultipartRequest,
 options?: SecondParameter<typeof orvalMutator<FileResult>>,) => {
      return orvalMutator<FileResult>(
      {url: `/api/v1/files/multipart/complete`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: completeMultipartRequest
    },
      options);
    }

const completeUpload = (
    completeUploadRequest: CompleteUploadRequest,
 options?: SecondParameter<typeof orvalMutator<FileResult>>,) => {
      return orvalMutator<FileResult>(
      {url: `/api/v1/files/complete-upload`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: completeUploadRequest
    },
      options);
    }

const getAll = (

 options?: SecondParameter<typeof orvalMutator<FileCategoryResult[]>>,) => {
      return orvalMutator<FileCategoryResult[]>(
      {url: `/api/v1/file-categories`, method: 'GET'
    },
      options);
    }

const create1 = (
    createFileCategoryRequest?: CreateFileCategoryRequest,
 options?: SecondParameter<typeof orvalMutator<FileCategoryResult>>,) => {
      return orvalMutator<FileCategoryResult>(
      {url: `/api/v1/file-categories`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createFileCategoryRequest
    },
      options);
    }

const addContentType = (
    id: number,
    addContentTypeRequest?: AddContentTypeRequest,
 options?: SecondParameter<typeof orvalMutator<void>>,) => {
      return orvalMutator<void>(
      {url: `/api/v1/file-categories/${id}/content-types`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addContentTypeRequest
    },
      options);
    }

const getAll1 = (

 options?: SecondParameter<typeof orvalMutator<FileAttributeResult[]>>,) => {
      return orvalMutator<FileAttributeResult[]>(
      {url: `/api/v1/file-attributes`, method: 'GET'
    },
      options);
    }

const create2 = (
    createFileAttributeRequest?: CreateFileAttributeRequest,
 options?: SecondParameter<typeof orvalMutator<FileAttributeResult>>,) => {
      return orvalMutator<FileAttributeResult>(
      {url: `/api/v1/file-attributes`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createFileAttributeRequest
    },
      options);
    }

const addOption = (
    id: number,
    addOptionRequest?: AddOptionRequest,
 options?: SecondParameter<typeof orvalMutator<void>>,) => {
      return orvalMutator<void>(
      {url: `/api/v1/file-attributes/${id}/options`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addOptionRequest
    },
      options);
    }

const list = (
    params: ListParams,
 options?: SecondParameter<typeof orvalMutator<PageFileResult>>,) => {
      return orvalMutator<PageFileResult>(
      {url: `/api/v1/files`, method: 'GET',
        params
    },
      options);
    }

const presignedDownload = (
    id: number,
 options?: SecondParameter<typeof orvalMutator<string>>,) => {
      return orvalMutator<string>(
      {url: `/api/v1/files/${id}/presigned-download`, method: 'GET'
    },
      options);
    }

return {get,update,_delete,update1,create,update2,presignedUpload,presignedPart,init,complete,completeUpload,getAll,create1,addContentType,getAll1,create2,addOption,list,presignedDownload}};
export type GetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEDocumentAPI>['get']>>>
export type UpdateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEDocumentAPI>['update']>>>
export type _DeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEDocumentAPI>['_delete']>>>
export type Update1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getEDocumentAPI>['update1']>>>
export type CreateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEDocumentAPI>['create']>>>
export type Update2Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getEDocumentAPI>['update2']>>>
export type PresignedUploadResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEDocumentAPI>['presignedUpload']>>>
export type PresignedPartResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEDocumentAPI>['presignedPart']>>>
export type InitResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEDocumentAPI>['init']>>>
export type CompleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEDocumentAPI>['complete']>>>
export type CompleteUploadResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEDocumentAPI>['completeUpload']>>>
export type GetAllResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEDocumentAPI>['getAll']>>>
export type Create1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getEDocumentAPI>['create1']>>>
export type AddContentTypeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEDocumentAPI>['addContentType']>>>
export type GetAll1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getEDocumentAPI>['getAll1']>>>
export type Create2Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getEDocumentAPI>['create2']>>>
export type AddOptionResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEDocumentAPI>['addOption']>>>
export type ListResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEDocumentAPI>['list']>>>
export type PresignedDownloadResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEDocumentAPI>['presignedDownload']>>>
