/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * E-Document API
 * API documentation for the E-Document service
 * OpenAPI spec version: v1
 */
import { orvalMutator } from '../../lib/orvalMutatorDocument';
export interface CreateFileRequest {
  fileName?: string;
  contentType?: string;
  categoryCode?: string;
}

export interface FileResult {
  id?: number;
  fileName?: string;
  contentType?: string;
  size?: number;
  createdAt?: string;
}

export interface FileAttributeValueRequest {
  key?: string;
  value?: unknown;
}

export interface FileAttributeValuesRequest {
  attributes?: FileAttributeValueRequest[];
}

export interface UpdateFileCategoryRequest {
  name?: string;
  maxSize?: number;
  bucketName?: string;
  retentionDays?: number;
  isPublic?: boolean;
}

export interface FileCategoryResult {
  id?: number;
  code?: string;
  name?: string;
  isPublic?: boolean;
}

export interface PresignedUploadRequest {
  fileName?: string;
  contentType?: string;
  categoryCode?: string;
}

export interface PresignedUploadResult {
  uploadUrl?: string;
  objectKey?: string;
  bucket?: string;
}

export interface PresignedPartRequest {
  bucket?: string;
  objectKey?: string;
  uploadId?: string;
  partNumber?: number;
}

export interface PresignedPartResult {
  url?: string;
}

export interface InitiateMultipartRequest {
  categoryCode?: string;
  fileName?: string;
}

export interface InitiateMultipartResult {
  uploadId?: string;
  objectKey?: string;
  bucket?: string;
}

export interface PartETag {
  partNumber?: number;
  etag?: string;
}

export interface CompleteMultipartRequest {
  objectKey?: string;
  uploadId?: string;
  parts?: PartETag[];
  fileName?: string;
  categoryCode?: string;
  contentType?: string;
  size?: number;
}

export interface CompleteUploadRequest {
  objectKey?: string;
  fileName?: string;
  size?: number;
  contentType?: string;
  categoryCode?: string;
}

export interface CreateFileCategoryRequest {
  code?: string;
  name?: string;
  maxSize?: number;
  bucketName?: string;
  retentionDays?: number;
  isPublic?: boolean;
}

export interface AddContentTypeRequest {
  contentType?: string;
}

export type CreateFileAttributeRequestDataType = typeof CreateFileAttributeRequestDataType[keyof typeof CreateFileAttributeRequestDataType];


export const CreateFileAttributeRequestDataType = {
  STRING: 'STRING',
  NUMBER: 'NUMBER',
  DATE: 'DATE',
  BOOLEAN: 'BOOLEAN',
  LIST: 'LIST',
} as const;

export interface CreateFileAttributeRequest {
  keyCode?: string;
  displayName?: string;
  dataType?: CreateFileAttributeRequestDataType;
  isRequired?: boolean;
}

export type FileAttributeResultDataType = typeof FileAttributeResultDataType[keyof typeof FileAttributeResultDataType];


export const FileAttributeResultDataType = {
  STRING: 'STRING',
  NUMBER: 'NUMBER',
  DATE: 'DATE',
  BOOLEAN: 'BOOLEAN',
  LIST: 'LIST',
} as const;

export interface FileAttributeResult {
  id?: number;
  keyCode?: string;
  displayName?: string;
  dataType?: FileAttributeResultDataType;
  isRequired?: boolean;
}

export interface AddOptionRequest {
  optionLabel?: string;
  optionValue?: string;
  sortOrder?: number;
}

export interface Pageable {
  /** @minimum 0 */
  page?: number;
  /** @minimum 1 */
  size?: number;
  sort?: string[];
}

export interface SortObject {
  empty?: boolean;
  sorted?: boolean;
  unsorted?: boolean;
}

export interface PageableObject {
  offset?: number;
  sort?: SortObject;
  pageSize?: number;
  pageNumber?: number;
  paged?: boolean;
  unpaged?: boolean;
}

export interface PageFileResult {
  totalPages?: number;
  totalElements?: number;
  size?: number;
  content?: FileResult[];
  number?: number;
  sort?: SortObject;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  pageable?: PageableObject;
  empty?: boolean;
}

export type ListFilesParams = {
pageable: Pageable;
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getEDocumentAPI = () => {
/**
 * Returns the file metadata for the requested identifier.
 * @summary Get a file
 */
const getFile = (
    id: number,
 options?: SecondParameter<typeof orvalMutator<FileResult>>,) => {
      return orvalMutator<FileResult>(
      {url: `/api/v1/files/${id}`, method: 'GET'
    },
      options);
    }

/**
 * Updates the file name for the requested file.
 * @summary Update a file
 */
const updateFile = (
    id: number,
    createFileRequest: CreateFileRequest,
 options?: SecondParameter<typeof orvalMutator<FileResult>>,) => {
      return orvalMutator<FileResult>(
      {url: `/api/v1/files/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: createFileRequest
    },
      options);
    }

/**
 * Deletes the requested file.
 * @summary Delete a file
 */
const deleteFile = (
    id: number,
 options?: SecondParameter<typeof orvalMutator<void>>,) => {
      return orvalMutator<void>(
      {url: `/api/v1/files/${id}`, method: 'DELETE'
    },
      options);
    }

/**
 * Updates attribute values for a file.
 * @summary Update attribute values
 */
const updateFileAttributeValues = (
    fileId: number,
    fileAttributeValuesRequest?: FileAttributeValuesRequest,
 options?: SecondParameter<typeof orvalMutator<void>>,) => {
      return orvalMutator<void>(
      {url: `/api/v1/files/${fileId}/attributes`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: fileAttributeValuesRequest
    },
      options);
    }

/**
 * Creates attribute values for a file.
 * @summary Create attribute values
 */
const createFileAttributeValues = (
    fileId: number,
    fileAttributeValuesRequest?: FileAttributeValuesRequest,
 options?: SecondParameter<typeof orvalMutator<void>>,) => {
      return orvalMutator<void>(
      {url: `/api/v1/files/${fileId}/attributes`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: fileAttributeValuesRequest
    },
      options);
    }

/**
 * Updates an existing file category.
 * @summary Update a file category
 */
const updateFileCategory = (
    id: number,
    updateFileCategoryRequest?: UpdateFileCategoryRequest,
 options?: SecondParameter<typeof orvalMutator<FileCategoryResult>>,) => {
      return orvalMutator<FileCategoryResult>(
      {url: `/api/v1/file-categories/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateFileCategoryRequest
    },
      options);
    }

/**
 * Generates a presigned upload URL for a file.
 * @summary Create a presigned upload
 */
const createPresignedUpload = (
    presignedUploadRequest: PresignedUploadRequest,
 options?: SecondParameter<typeof orvalMutator<PresignedUploadResult>>,) => {
      return orvalMutator<PresignedUploadResult>(
      {url: `/api/v1/files/presigned-upload`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: presignedUploadRequest
    },
      options);
    }

/**
 * Generates a presigned URL for uploading one multipart segment.
 * @summary Create a presigned multipart part
 */
const createPresignedPart = (
    presignedPartRequest: PresignedPartRequest,
 options?: SecondParameter<typeof orvalMutator<PresignedPartResult>>,) => {
      return orvalMutator<PresignedPartResult>(
      {url: `/api/v1/files/multipart/presigned-part`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: presignedPartRequest
    },
      options);
    }

/**
 * Starts a multipart upload flow for a file category.
 * @summary Initiate a multipart upload
 */
const initMultipartUpload = (
    initiateMultipartRequest: InitiateMultipartRequest,
 options?: SecondParameter<typeof orvalMutator<InitiateMultipartResult>>,) => {
      return orvalMutator<InitiateMultipartResult>(
      {url: `/api/v1/files/multipart/init`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: initiateMultipartRequest
    },
      options);
    }

/**
 * Completes a multipart upload and returns the stored file metadata.
 * @summary Complete a multipart upload
 */
const completeMultipartUpload = (
    completeMultipartRequest: CompleteMultipartRequest,
 options?: SecondParameter<typeof orvalMutator<FileResult>>,) => {
      return orvalMutator<FileResult>(
      {url: `/api/v1/files/multipart/complete`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: completeMultipartRequest
    },
      options);
    }

/**
 * Completes a direct upload and persists the resulting file metadata.
 * @summary Complete a file upload
 */
const completeUpload = (
    completeUploadRequest: CompleteUploadRequest,
 options?: SecondParameter<typeof orvalMutator<FileResult>>,) => {
      return orvalMutator<FileResult>(
      {url: `/api/v1/files/complete-upload`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: completeUploadRequest
    },
      options);
    }

/**
 * Returns all configured file categories.
 * @summary List file categories
 */
const listFileCategories = (

 options?: SecondParameter<typeof orvalMutator<FileCategoryResult[]>>,) => {
      return orvalMutator<FileCategoryResult[]>(
      {url: `/api/v1/file-categories`, method: 'GET'
    },
      options);
    }

/**
 * Creates a new file category.
 * @summary Create a file category
 */
const createFileCategory = (
    createFileCategoryRequest?: CreateFileCategoryRequest,
 options?: SecondParameter<typeof orvalMutator<FileCategoryResult>>,) => {
      return orvalMutator<FileCategoryResult>(
      {url: `/api/v1/file-categories`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createFileCategoryRequest
    },
      options);
    }

/**
 * Adds a supported content type to a file category.
 * @summary Add a content type
 */
const addFileCategoryContentType = (
    id: number,
    addContentTypeRequest?: AddContentTypeRequest,
 options?: SecondParameter<typeof orvalMutator<void>>,) => {
      return orvalMutator<void>(
      {url: `/api/v1/file-categories/${id}/content-types`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addContentTypeRequest
    },
      options);
    }

/**
 * Returns all configured file attributes.
 * @summary List file attributes
 */
const listFileAttributes = (

 options?: SecondParameter<typeof orvalMutator<FileAttributeResult[]>>,) => {
      return orvalMutator<FileAttributeResult[]>(
      {url: `/api/v1/file-attributes`, method: 'GET'
    },
      options);
    }

/**
 * Creates a new file attribute definition.
 * @summary Create a file attribute
 */
const createFileAttribute = (
    createFileAttributeRequest?: CreateFileAttributeRequest,
 options?: SecondParameter<typeof orvalMutator<FileAttributeResult>>,) => {
      return orvalMutator<FileAttributeResult>(
      {url: `/api/v1/file-attributes`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createFileAttributeRequest
    },
      options);
    }

/**
 * Adds an option to a file attribute.
 * @summary Add an option
 */
const addFileAttributeOption = (
    id: number,
    addOptionRequest?: AddOptionRequest,
 options?: SecondParameter<typeof orvalMutator<void>>,) => {
      return orvalMutator<void>(
      {url: `/api/v1/file-attributes/${id}/options`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addOptionRequest
    },
      options);
    }

/**
 * Returns a paginated list of files.
 * @summary List files
 */
const listFiles = (
    params: ListFilesParams,
 options?: SecondParameter<typeof orvalMutator<PageFileResult>>,) => {
      return orvalMutator<PageFileResult>(
      {url: `/api/v1/files`, method: 'GET',
        params
    },
      options);
    }

/**
 * Generates a presigned download URL for the requested file.
 * @summary Create a presigned download
 */
const createPresignedDownload = (
    id: number,
 options?: SecondParameter<typeof orvalMutator<string>>,) => {
      return orvalMutator<string>(
      {url: `/api/v1/files/${id}/presigned-download`, method: 'GET'
    },
      options);
    }

return {getFile,updateFile,deleteFile,updateFileAttributeValues,createFileAttributeValues,updateFileCategory,createPresignedUpload,createPresignedPart,initMultipartUpload,completeMultipartUpload,completeUpload,listFileCategories,createFileCategory,addFileCategoryContentType,listFileAttributes,createFileAttribute,addFileAttributeOption,listFiles,createPresignedDownload}};
export type GetFileResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEDocumentAPI>['getFile']>>>
export type UpdateFileResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEDocumentAPI>['updateFile']>>>
export type DeleteFileResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEDocumentAPI>['deleteFile']>>>
export type UpdateFileAttributeValuesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEDocumentAPI>['updateFileAttributeValues']>>>
export type CreateFileAttributeValuesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEDocumentAPI>['createFileAttributeValues']>>>
export type UpdateFileCategoryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEDocumentAPI>['updateFileCategory']>>>
export type CreatePresignedUploadResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEDocumentAPI>['createPresignedUpload']>>>
export type CreatePresignedPartResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEDocumentAPI>['createPresignedPart']>>>
export type InitMultipartUploadResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEDocumentAPI>['initMultipartUpload']>>>
export type CompleteMultipartUploadResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEDocumentAPI>['completeMultipartUpload']>>>
export type CompleteUploadResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEDocumentAPI>['completeUpload']>>>
export type ListFileCategoriesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEDocumentAPI>['listFileCategories']>>>
export type CreateFileCategoryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEDocumentAPI>['createFileCategory']>>>
export type AddFileCategoryContentTypeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEDocumentAPI>['addFileCategoryContentType']>>>
export type ListFileAttributesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEDocumentAPI>['listFileAttributes']>>>
export type CreateFileAttributeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEDocumentAPI>['createFileAttribute']>>>
export type AddFileAttributeOptionResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEDocumentAPI>['addFileAttributeOption']>>>
export type ListFilesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEDocumentAPI>['listFiles']>>>
export type CreatePresignedDownloadResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEDocumentAPI>['createPresignedDownload']>>>
