replicaCount: 1

image:
  repository: viennn/discovery-server
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8761

containerPort: 8761

env:
  SPRING_PROFILES_ACTIVE: local
  SERVER_PORT: "8761"
