spring:
  application:
    name: identity-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/identity_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true # On/Off liquibase
    default-schema: public
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8080/realms/your-realm}

server:
  port: ${SERVER_PORT:8081}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# Config for Keycloak Admin Client
keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:http://localhost:8080}
  realm: ${KEYCLOAK_REALM:your-realm}
  client-id: ${KEYCLOAK_CLIENT_ID:admin-cli}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:your-client-secret}
