apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: connector-service-prod
  namespace: argocd

spec:
  project: backend-services

  source:
    repoURL: https://github.com/nguyenngocvien/business-workflow-automation.git
    targetRevision: main
    path: gitops/apps/connector-service

    helm:
      valueFiles:
        - ../../environments/prod/connector-service/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
