apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres.yaml
  - elasticsearch.yaml
  - zeebe.yaml
  - operate.yaml
  - tasklist.yaml
  - keycloak.yaml
  - minio.yaml
  - rabbitmq.yaml
