/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * E-Document API
 * API documentation for the E-Document service
 * OpenAPI spec version: v1
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
export interface SortObject {
  empty?: boolean;
  sorted?: boolean;
  unsorted?: boolean;
}

export interface PageableObject {
  offset?: number;
  paged?: boolean;
  pageNumber?: number;
  pageSize?: number;
  sort?: SortObject;
  unpaged?: boolean;
}

export interface PageFileResult {
  content?: FileResult[];
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  pageable?: PageableObject;
  size?: number;
  sort?: SortObject;
  totalElements?: number;
  totalPages?: number;
}

export interface Pageable {
  /** @minimum 0 */
  page?: number;
  /** @minimum 1 */
  size?: number;
  sort?: string[];
}

export type ListParams = {
pageable: Pageable;
};

export interface AddOptionRequest {
  optionLabel?: string;
  optionValue?: string;
  sortOrder?: number;
}

export type FileAttributeResultDataType = typeof FileAttributeResultDataType[keyof typeof FileAttributeResultDataType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FileAttributeResultDataType = {
  STRING: 'STRING',
  NUMBER: 'NUMBER',
  DATE: 'DATE',
  BOOLEAN: 'BOOLEAN',
  LIST: 'LIST',
} as const;

export interface FileAttributeResult {
  dataType?: FileAttributeResultDataType;
  displayName?: string;
  id?: number;
  isRequired?: boolean;
  keyCode?: string;
}

export type CreateFileAttributeRequestDataType = typeof CreateFileAttributeRequestDataType[keyof typeof CreateFileAttributeRequestDataType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateFileAttributeRequestDataType = {
  STRING: 'STRING',
  NUMBER: 'NUMBER',
  DATE: 'DATE',
  BOOLEAN: 'BOOLEAN',
  LIST: 'LIST',
} as const;

export interface CreateFileAttributeRequest {
  dataType?: CreateFileAttributeRequestDataType;
  displayName?: string;
  isRequired?: boolean;
  keyCode?: string;
}

export interface AddContentTypeRequest {
  contentType?: string;
}

export interface CreateFileCategoryRequest {
  bucketName?: string;
  code?: string;
  isPublic?: boolean;
  maxSize?: number;
  name?: string;
  retentionDays?: number;
}

export interface CompleteUploadRequest {
  categoryCode?: string;
  contentType?: string;
  fileName?: string;
  objectKey?: string;
  size?: number;
}

export interface PartETag {
  etag?: string;
  partNumber?: number;
}

export interface CompleteMultipartRequest {
  categoryCode?: string;
  contentType?: string;
  fileName?: string;
  objectKey?: string;
  parts?: PartETag[];
  size?: number;
  uploadId?: string;
}

export interface InitiateMultipartResult {
  bucket?: string;
  objectKey?: string;
  uploadId?: string;
}

export interface InitiateMultipartRequest {
  categoryCode?: string;
  fileName?: string;
}

export interface PresignedPartResult {
  url?: string;
}

export interface PresignedPartRequest {
  bucket?: string;
  objectKey?: string;
  partNumber?: number;
  uploadId?: string;
}

export interface PresignedUploadResult {
  bucket?: string;
  objectKey?: string;
  uploadUrl?: string;
}

export interface PresignedUploadRequest {
  categoryCode?: string;
  contentType?: string;
  fileName?: string;
}

export interface FileCategoryResult {
  code?: string;
  id?: number;
  isPublic?: boolean;
  name?: string;
}

export interface UpdateFileCategoryRequest {
  bucketName?: string;
  isPublic?: boolean;
  maxSize?: number;
  name?: string;
  retentionDays?: number;
}

export interface FileAttributeValueRequest {
  key?: string;
  value?: unknown;
}

export interface FileAttributeValuesRequest {
  attributes?: FileAttributeValueRequest[];
}

export interface FileResult {
  contentType?: string;
  createdAt?: string;
  fileName?: string;
  id?: number;
  size?: number;
}

export interface CreateFileRequest {
  categoryCode?: string;
  contentType?: string;
  fileName?: string;
}





  export const getEDocumentAPI = () => {
const get = <TData = AxiosResponse<FileResult>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/files/${id}`,options
    );
  }

const update = <TData = AxiosResponse<FileResult>>(
    id: number,
    createFileRequest: CreateFileRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/v1/files/${id}`,
      createFileRequest,options
    );
  }

const _delete = <TData = AxiosResponse<void>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/v1/files/${id}`,options
    );
  }

const update1 = <TData = AxiosResponse<void>>(
    fileId: number,
    fileAttributeValuesRequest: FileAttributeValuesRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/v1/files/${fileId}/attributes`,
      fileAttributeValuesRequest,options
    );
  }

const create = <TData = AxiosResponse<void>>(
    fileId: number,
    fileAttributeValuesRequest: FileAttributeValuesRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/files/${fileId}/attributes`,
      fileAttributeValuesRequest,options
    );
  }

const update2 = <TData = AxiosResponse<FileCategoryResult>>(
    id: number,
    updateFileCategoryRequest: UpdateFileCategoryRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/v1/file-categories/${id}`,
      updateFileCategoryRequest,options
    );
  }

const presignedUpload = <TData = AxiosResponse<PresignedUploadResult>>(
    presignedUploadRequest: PresignedUploadRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/files/presigned-upload`,
      presignedUploadRequest,options
    );
  }

const presignedPart = <TData = AxiosResponse<PresignedPartResult>>(
    presignedPartRequest: PresignedPartRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/files/multipart/presigned-part`,
      presignedPartRequest,options
    );
  }

const init = <TData = AxiosResponse<InitiateMultipartResult>>(
    initiateMultipartRequest: InitiateMultipartRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/files/multipart/init`,
      initiateMultipartRequest,options
    );
  }

const complete = <TData = AxiosResponse<FileResult>>(
    completeMultipartRequest: CompleteMultipartRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/files/multipart/complete`,
      completeMultipartRequest,options
    );
  }

const completeUpload = <TData = AxiosResponse<FileResult>>(
    completeUploadRequest: CompleteUploadRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/files/complete-upload`,
      completeUploadRequest,options
    );
  }

const getAll = <TData = AxiosResponse<FileCategoryResult[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/file-categories`,options
    );
  }

const create1 = <TData = AxiosResponse<FileCategoryResult>>(
    createFileCategoryRequest: CreateFileCategoryRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/file-categories`,
      createFileCategoryRequest,options
    );
  }

const addContentType = <TData = AxiosResponse<void>>(
    id: number,
    addContentTypeRequest: AddContentTypeRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/file-categories/${id}/content-types`,
      addContentTypeRequest,options
    );
  }

const getAll1 = <TData = AxiosResponse<FileAttributeResult[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/file-attributes`,options
    );
  }

const create2 = <TData = AxiosResponse<FileAttributeResult>>(
    createFileAttributeRequest: CreateFileAttributeRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/file-attributes`,
      createFileAttributeRequest,options
    );
  }

const addOption = <TData = AxiosResponse<void>>(
    id: number,
    addOptionRequest: AddOptionRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/file-attributes/${id}/options`,
      addOptionRequest,options
    );
  }

const list = <TData = AxiosResponse<PageFileResult>>(
    params: ListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/files`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const presignedDownload = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/files/${id}/presigned-download`,options
    );
  }

return {get,update,_delete,update1,create,update2,presignedUpload,presignedPart,init,complete,completeUpload,getAll,create1,addContentType,getAll1,create2,addOption,list,presignedDownload}};
export type GetResult = AxiosResponse<FileResult>
export type UpdateResult = AxiosResponse<FileResult>
export type _DeleteResult = AxiosResponse<void>
export type Update1Result = AxiosResponse<void>
export type CreateResult = AxiosResponse<void>
export type Update2Result = AxiosResponse<FileCategoryResult>
export type PresignedUploadResult = AxiosResponse<PresignedUploadResult>
export type PresignedPartResult = AxiosResponse<PresignedPartResult>
export type InitResult = AxiosResponse<InitiateMultipartResult>
export type CompleteResult = AxiosResponse<FileResult>
export type CompleteUploadResult = AxiosResponse<FileResult>
export type GetAllResult = AxiosResponse<FileCategoryResult[]>
export type Create1Result = AxiosResponse<FileCategoryResult>
export type AddContentTypeResult = AxiosResponse<void>
export type GetAll1Result = AxiosResponse<FileAttributeResult[]>
export type Create2Result = AxiosResponse<FileAttributeResult>
export type AddOptionResult = AxiosResponse<void>
export type ListResult = AxiosResponse<PageFileResult>
export type PresignedDownloadResult = AxiosResponse<string>
