replicaCount: 1

image:
  repository: viennn/api-gateway
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

containerPort: 8080

ingress:
  enabled: true
  className: nginx
  host: gateway.dev.localtest.me
  path: /
  pathType: Prefix

env:
  SPRING_PROFILES_ACTIVE: local
  SERVER_PORT: "8080"
  EUREKA_DEFAULT_ZONE: http://discovery-server:8761/eureka/
  JWT_ISSUER_URI: http://keycloak:8080/realms/my-realm
  JWT_JWK_SET_URI: http://keycloak:8080/realms/my-realm/protocol/openid-connect/certs
