/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * E-Connector API
 * Connector Platform API
 * OpenAPI spec version: 1.0
 */
import findByIdMutator from '../../lib/orvalMutator';
import updateMutator from '../../lib/orvalMutator';
import _deleteMutator from '../../lib/orvalMutator';
import findById1Mutator from '../../lib/orvalMutator';
import update1Mutator from '../../lib/orvalMutator';
import delete1Mutator from '../../lib/orvalMutator';
import findById2Mutator from '../../lib/orvalMutator';
import update2Mutator from '../../lib/orvalMutator';
import delete2Mutator from '../../lib/orvalMutator';
import findById3Mutator from '../../lib/orvalMutator';
import update3Mutator from '../../lib/orvalMutator';
import delete3Mutator from '../../lib/orvalMutator';
import findById4Mutator from '../../lib/orvalMutator';
import update4Mutator from '../../lib/orvalMutator';
import delete4Mutator from '../../lib/orvalMutator';
import findById5Mutator from '../../lib/orvalMutator';
import update5Mutator from '../../lib/orvalMutator';
import delete5Mutator from '../../lib/orvalMutator';
import findById6Mutator from '../../lib/orvalMutator';
import update6Mutator from '../../lib/orvalMutator';
import delete6Mutator from '../../lib/orvalMutator';
import findAllMutator from '../../lib/orvalMutator';
import createMutator from '../../lib/orvalMutator';
import findAll1Mutator from '../../lib/orvalMutator';
import create1Mutator from '../../lib/orvalMutator';
import findAll2Mutator from '../../lib/orvalMutator';
import create2Mutator from '../../lib/orvalMutator';
import findAll3Mutator from '../../lib/orvalMutator';
import create3Mutator from '../../lib/orvalMutator';
import findAll4Mutator from '../../lib/orvalMutator';
import create4Mutator from '../../lib/orvalMutator';
import executeMutator from '../../lib/orvalMutator';
import findAll5Mutator from '../../lib/orvalMutator';
import create5Mutator from '../../lib/orvalMutator';
import findAll6Mutator from '../../lib/orvalMutator';
import create6Mutator from '../../lib/orvalMutator';
import getSchemaMutator from '../../lib/orvalMutator';
import findAll7Mutator from '../../lib/orvalMutator';
import findById7Mutator from '../../lib/orvalMutator';
import findAll8Mutator from '../../lib/orvalMutator';
import findByNameMutator from '../../lib/orvalMutator';
import getSchema1Mutator from '../../lib/orvalMutator';
export type UpdateServiceRequestServiceType = typeof UpdateServiceRequestServiceType[keyof typeof UpdateServiceRequestServiceType];


export const UpdateServiceRequestServiceType = {
  REST: 'REST',
  DB: 'DB',
  PIPELINE: 'PIPELINE',
  EMAIL: 'EMAIL',
} as const;

export type UpdateServiceRequestConfig = {[key: string]: unknown};

export interface UpdateServiceRequest {
  /**
     * @minLength 0
     * @maxLength 255
     */
  serviceName?: string;
  serviceType?: UpdateServiceRequestServiceType;
  /**
     * @minLength 0
     * @maxLength 50
     */
  serviceVersion?: string;
  /**
     * @minLength 0
     * @maxLength 100
     */
  appId?: string;
  connectionId?: number;
  config?: UpdateServiceRequestConfig;
  timeoutMs?: number;
  retryCount?: number;
  active?: boolean;
  logEnable?: boolean;
  /**
     * @minLength 0
     * @maxLength 100
     */
  updatedBy?: string;
}

export interface ServiceConfig {}

export type ServiceResultServiceType = typeof ServiceResultServiceType[keyof typeof ServiceResultServiceType];


export const ServiceResultServiceType = {
  REST: 'REST',
  DB: 'DB',
  PIPELINE: 'PIPELINE',
  EMAIL: 'EMAIL',
} as const;

export interface ServiceResult {
  id?: number;
  serviceCode?: string;
  serviceName?: string;
  serviceType?: ServiceResultServiceType;
  serviceVersion?: string;
  appId?: string;
  connectionId?: number;
  configJson?: string;
  config?: ServiceConfig;
  timeoutMs?: number;
  retryCount?: number;
  active?: boolean;
  logEnable?: boolean;
  createdBy?: string;
  updatedBy?: string;
  createdAt?: string;
  updatedAt?: string;
}

export type UpdateScheduleJobRequestJobType = typeof UpdateScheduleJobRequestJobType[keyof typeof UpdateScheduleJobRequestJobType];


export const UpdateScheduleJobRequestJobType = {
  SERVICE: 'SERVICE',
  PIPELINE: 'PIPELINE',
} as const;

export interface UpdateScheduleJobRequest {
  /**
     * @minLength 0
     * @maxLength 255
     */
  jobName?: string;
  jobType?: UpdateScheduleJobRequestJobType;
  serviceId?: number;
  pipelineId?: number;
  /**
     * @minLength 0
     * @maxLength 50
     */
  cronExpression?: string;
  fixedRateMs?: number;
  enabled?: boolean;
}

export type ScheduleJobResultJobType = typeof ScheduleJobResultJobType[keyof typeof ScheduleJobResultJobType];


export const ScheduleJobResultJobType = {
  SERVICE: 'SERVICE',
  PIPELINE: 'PIPELINE',
} as const;

export interface ScheduleJobResult {
  id?: number;
  jobCode?: string;
  jobName?: string;
  jobType?: ScheduleJobResultJobType;
  serviceId?: number;
  pipelineId?: number;
  cronExpression?: string;
  fixedRateMs?: number;
  enabled?: boolean;
  lastRunTime?: string;
  nextRunTime?: string;
  createdAt?: string;
}

export interface UpdatePipelineRequest {
  /**
     * @minLength 0
     * @maxLength 255
     */
  pipelineName?: string;
  description?: string;
  active?: boolean;
}

export interface PipelineResult {
  id?: number;
  pipelineCode?: string;
  pipelineName?: string;
  description?: string;
  active?: boolean;
  createdAt?: string;
}

export interface UpdatePipelineStepRequest {
  stepOrder?: number;
  serviceId?: number;
  /**
     * @minLength 0
     * @maxLength 255
     */
  stepName?: string;
  requestTransform?: string;
  responseTransform?: string;
  continueOnError?: boolean;
}

export interface PipelineStepResult {
  id?: number;
  pipelineId?: number;
  stepOrder?: number;
  serviceId?: number;
  stepName?: string;
  requestTransform?: string;
  responseTransform?: string;
  continueOnError?: boolean;
  createdAt?: string;
}

export interface UpdateJobExecutionRequest {
  endTime?: string;
  /**
     * @minLength 0
     * @maxLength 50
     */
  status?: string;
  responseData?: string;
  errorMessage?: string;
}

export interface JobExecutionResult {
  id?: number;
  jobId?: number;
  startTime?: string;
  endTime?: string;
  status?: string;
  requestData?: string;
  responseData?: string;
  errorMessage?: string;
  createdAt?: string;
}

export interface UpdateEmailTemplateRequest {
  /**
     * @minLength 0
     * @maxLength 50
     */
  templateType?: string;
  /**
     * @minLength 0
     * @maxLength 255
     */
  title?: string;
  content?: string;
  status?: boolean;
  /**
     * @minLength 0
     * @maxLength 100
     */
  updatedBy?: string;
}

export interface EmailTemplateResult {
  id?: number;
  appId?: string;
  templateType?: string;
  templateCode?: string;
  title?: string;
  content?: string;
  status?: boolean;
  createdBy?: string;
  updatedBy?: string;
  createdAt?: string;
  updatedAt?: string;
}

export type UpdateConnectionRequestConnectionType = typeof UpdateConnectionRequestConnectionType[keyof typeof UpdateConnectionRequestConnectionType];


export const UpdateConnectionRequestConnectionType = {
  DB: 'DB',
  REST: 'REST',
  SOAP: 'SOAP',
  SFTP: 'SFTP',
  SMTP: 'SMTP',
  KAFKA: 'KAFKA',
} as const;

export type UpdateConnectionRequestConfig = {[key: string]: unknown};

export interface UpdateConnectionRequest {
  connectionName?: string;
  connectionType?: UpdateConnectionRequestConnectionType;
  config?: UpdateConnectionRequestConfig;
  active?: boolean;
}

export interface ConnectionConfig {}

export type ConnectionResultConnectionType = typeof ConnectionResultConnectionType[keyof typeof ConnectionResultConnectionType];


export const ConnectionResultConnectionType = {
  DB: 'DB',
  REST: 'REST',
  SOAP: 'SOAP',
  SFTP: 'SFTP',
  SMTP: 'SMTP',
  KAFKA: 'KAFKA',
} as const;

export interface ConnectionResult {
  id?: number;
  connectionCode?: string;
  connectionName?: string;
  connectionType?: ConnectionResultConnectionType;
  configJson?: string;
  config?: ConnectionConfig;
  active?: boolean;
  createdAt?: string;
  updatedAt?: string;
}

export type CreateServiceRequestServiceType = typeof CreateServiceRequestServiceType[keyof typeof CreateServiceRequestServiceType];


export const CreateServiceRequestServiceType = {
  REST: 'REST',
  DB: 'DB',
  PIPELINE: 'PIPELINE',
  EMAIL: 'EMAIL',
} as const;

export type CreateServiceRequestConfig = {[key: string]: unknown};

export interface CreateServiceRequest {
  /**
     * @minLength 0
     * @maxLength 100
     */
  serviceCode: string;
  /**
     * @minLength 0
     * @maxLength 255
     */
  serviceName?: string;
  serviceType: CreateServiceRequestServiceType;
  /**
     * @minLength 0
     * @maxLength 50
     */
  serviceVersion?: string;
  /**
     * @minLength 0
     * @maxLength 100
     */
  appId?: string;
  connectionId?: number;
  config?: CreateServiceRequestConfig;
  timeoutMs?: number;
  retryCount?: number;
  active?: boolean;
  logEnable?: boolean;
  /**
     * @minLength 0
     * @maxLength 100
     */
  createdBy?: string;
}

export type CreateScheduleJobRequestJobType = typeof CreateScheduleJobRequestJobType[keyof typeof CreateScheduleJobRequestJobType];


export const CreateScheduleJobRequestJobType = {
  SERVICE: 'SERVICE',
  PIPELINE: 'PIPELINE',
} as const;

export interface CreateScheduleJobRequest {
  /**
     * @minLength 0
     * @maxLength 100
     */
  jobCode: string;
  /**
     * @minLength 0
     * @maxLength 255
     */
  jobName: string;
  jobType: CreateScheduleJobRequestJobType;
  serviceId?: number;
  pipelineId?: number;
  /**
     * @minLength 0
     * @maxLength 50
     */
  cronExpression?: string;
  fixedRateMs?: number;
  enabled?: boolean;
}

export interface CreatePipelineRequest {
  /**
     * @minLength 0
     * @maxLength 100
     */
  pipelineCode: string;
  /**
     * @minLength 0
     * @maxLength 255
     */
  pipelineName: string;
  description?: string;
  active?: boolean;
}

export interface CreatePipelineStepRequest {
  pipelineId: number;
  stepOrder: number;
  serviceId: number;
  /**
     * @minLength 0
     * @maxLength 255
     */
  stepName?: string;
  requestTransform?: string;
  responseTransform?: string;
  continueOnError?: boolean;
}

export interface CreateJobExecutionRequest {
  jobId: number;
  startTime?: string;
  requestData?: string;
}

export type ExecuteServiceRequestHeaders = {[key: string]: string};

export interface JsonNode {}

export interface ExecuteServiceRequest {
  headers?: ExecuteServiceRequestHeaders;
  payload?: JsonNode;
}

export type ExecuteServiceResponseServiceType = typeof ExecuteServiceResponseServiceType[keyof typeof ExecuteServiceResponseServiceType];


export const ExecuteServiceResponseServiceType = {
  REST: 'REST',
  DB: 'DB',
  PIPELINE: 'PIPELINE',
  EMAIL: 'EMAIL',
} as const;

export type ExecuteServiceResponseResponseHeaders = {[key: string]: string[]};

export interface ExecuteServiceResponse {
  serviceId?: number;
  appId?: string;
  serviceCode?: string;
  serviceVersion?: string;
  serviceType?: ExecuteServiceResponseServiceType;
  statusCode?: number;
  responseHeaders?: ExecuteServiceResponseResponseHeaders;
  body?: JsonNode;
}

export interface CreateEmailTemplateRequest {
  /**
     * @minLength 0
     * @maxLength 100
     */
  appId: string;
  /**
     * @minLength 0
     * @maxLength 50
     */
  templateType: string;
  /**
     * @minLength 0
     * @maxLength 100
     */
  templateCode: string;
  /**
     * @minLength 0
     * @maxLength 255
     */
  title: string;
  /** @minLength 1 */
  content: string;
  status: boolean;
  /**
     * @minLength 0
     * @maxLength 100
     */
  createdBy?: string;
}

export type CreateConnectionRequestConnectionType = typeof CreateConnectionRequestConnectionType[keyof typeof CreateConnectionRequestConnectionType];


export const CreateConnectionRequestConnectionType = {
  DB: 'DB',
  REST: 'REST',
  SOAP: 'SOAP',
  SFTP: 'SFTP',
  SMTP: 'SMTP',
  KAFKA: 'KAFKA',
} as const;

export type CreateConnectionRequestConfig = {[key: string]: unknown};

export interface CreateConnectionRequest {
  /**
     * @minLength 0
     * @maxLength 100
     */
  connectionCode: string;
  /**
     * @minLength 0
     * @maxLength 255
     */
  connectionName: string;
  connectionType: CreateConnectionRequestConnectionType;
  config?: CreateConnectionRequestConfig;
  active?: boolean;
}

export interface SortObject {
  sorted?: boolean;
  empty?: boolean;
  unsorted?: boolean;
}

export interface PageableObject {
  paged?: boolean;
  pageNumber?: number;
  pageSize?: number;
  offset?: number;
  sort?: SortObject;
  unpaged?: boolean;
}

export interface PageServiceResult {
  totalPages?: number;
  totalElements?: number;
  pageable?: PageableObject;
  last?: boolean;
  first?: boolean;
  size?: number;
  content?: ServiceResult[];
  number?: number;
  sort?: SortObject;
  numberOfElements?: number;
  empty?: boolean;
}

export interface PageScheduleJobResult {
  totalPages?: number;
  totalElements?: number;
  pageable?: PageableObject;
  last?: boolean;
  first?: boolean;
  size?: number;
  content?: ScheduleJobResult[];
  number?: number;
  sort?: SortObject;
  numberOfElements?: number;
  empty?: boolean;
}

export interface PagePipelineResult {
  totalPages?: number;
  totalElements?: number;
  pageable?: PageableObject;
  last?: boolean;
  first?: boolean;
  size?: number;
  content?: PipelineResult[];
  number?: number;
  sort?: SortObject;
  numberOfElements?: number;
  empty?: boolean;
}

export interface PagePipelineStepResult {
  totalPages?: number;
  totalElements?: number;
  pageable?: PageableObject;
  last?: boolean;
  first?: boolean;
  size?: number;
  content?: PipelineStepResult[];
  number?: number;
  sort?: SortObject;
  numberOfElements?: number;
  empty?: boolean;
}

export interface LogResult {
  id?: number;
  serviceId?: number;
  traceId?: string;
  correlationId?: string;
  requestTime?: string;
  responseTime?: string;
  durationMs?: number;
  statusCode?: number;
  requestHeaders?: string;
  requestBody?: string;
  requestAfterTransform?: string;
  responseBody?: string;
  responseAfterTransform?: string;
  errorMessage?: string;
  stacktrace?: string;
  createdAt?: string;
}

export interface PageLogResult {
  totalPages?: number;
  totalElements?: number;
  pageable?: PageableObject;
  last?: boolean;
  first?: boolean;
  size?: number;
  content?: LogResult[];
  number?: number;
  sort?: SortObject;
  numberOfElements?: number;
  empty?: boolean;
}

export interface PageJobExecutionResult {
  totalPages?: number;
  totalElements?: number;
  pageable?: PageableObject;
  last?: boolean;
  first?: boolean;
  size?: number;
  content?: JobExecutionResult[];
  number?: number;
  sort?: SortObject;
  numberOfElements?: number;
  empty?: boolean;
}

export interface EnumOptionResponse {
  value?: string;
  label?: string;
}

export interface PageEmailTemplateResult {
  totalPages?: number;
  totalElements?: number;
  pageable?: PageableObject;
  last?: boolean;
  first?: boolean;
  size?: number;
  content?: EmailTemplateResult[];
  number?: number;
  sort?: SortObject;
  numberOfElements?: number;
  empty?: boolean;
}

export interface PageConnectionResult {
  totalPages?: number;
  totalElements?: number;
  pageable?: PageableObject;
  last?: boolean;
  first?: boolean;
  size?: number;
  content?: ConnectionResult[];
  number?: number;
  sort?: SortObject;
  numberOfElements?: number;
  empty?: boolean;
}

export type FindAllParams = {
/**
 * Zero-based page index (0..N)
 * @minimum 0
 */
page?: number;
/**
 * The size of the page to be returned
 * @minimum 1
 */
size?: number;
/**
 * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
 */
sort?: string[];
};

export type FindAll1Params = {
/**
 * Zero-based page index (0..N)
 * @minimum 0
 */
page?: number;
/**
 * The size of the page to be returned
 * @minimum 1
 */
size?: number;
/**
 * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
 */
sort?: string[];
};

export type FindAll2Params = {
/**
 * Zero-based page index (0..N)
 * @minimum 0
 */
page?: number;
/**
 * The size of the page to be returned
 * @minimum 1
 */
size?: number;
/**
 * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
 */
sort?: string[];
};

export type FindAll3Params = {
/**
 * Zero-based page index (0..N)
 * @minimum 0
 */
page?: number;
/**
 * The size of the page to be returned
 * @minimum 1
 */
size?: number;
/**
 * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
 */
sort?: string[];
};

export type FindAll4Params = {
/**
 * Zero-based page index (0..N)
 * @minimum 0
 */
page?: number;
/**
 * The size of the page to be returned
 * @minimum 1
 */
size?: number;
/**
 * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
 */
sort?: string[];
};

export type FindAll5Params = {
/**
 * Zero-based page index (0..N)
 * @minimum 0
 */
page?: number;
/**
 * The size of the page to be returned
 * @minimum 1
 */
size?: number;
/**
 * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
 */
sort?: string[];
};

export type FindAll6Params = {
/**
 * Zero-based page index (0..N)
 * @minimum 0
 */
page?: number;
/**
 * The size of the page to be returned
 * @minimum 1
 */
size?: number;
/**
 * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
 */
sort?: string[];
};

export type GetSchema200 = {[key: string]: unknown};

export type FindAll7Params = {
/**
 * Zero-based page index (0..N)
 * @minimum 0
 */
page?: number;
/**
 * The size of the page to be returned
 * @minimum 1
 */
size?: number;
/**
 * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
 */
sort?: string[];
};

export type FindAll8200 = {[key: string]: EnumOptionResponse[]};

export type GetSchema1200 = {[key: string]: unknown};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getEConnectorAPI = () => {
/**
 * @summary Get a service definition by id
 */
const findById = (
    id: number,
 options?: SecondParameter<typeof findByIdMutator<ServiceResult>>,) => {
      return findByIdMutator<ServiceResult>(
      {url: `/api/service-definitions/${id}`, method: 'GET'
    },
      options);
    }

/**
 * @summary Update a service definition
 */
const update = (
    id: number,
    updateServiceRequest: UpdateServiceRequest,
 options?: SecondParameter<typeof updateMutator<ServiceResult>>,) => {
      return updateMutator<ServiceResult>(
      {url: `/api/service-definitions/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateServiceRequest
    },
      options);
    }

/**
 * @summary Delete a service definition
 */
const _delete = (
    id: number,
 options?: SecondParameter<typeof _deleteMutator<void>>,) => {
      return _deleteMutator<void>(
      {url: `/api/service-definitions/${id}`, method: 'DELETE'
    },
      options);
    }

/**
 * @summary Get a scheduled job by id
 */
const findById1 = (
    id: number,
 options?: SecondParameter<typeof findById1Mutator<ScheduleJobResult>>,) => {
      return findById1Mutator<ScheduleJobResult>(
      {url: `/api/schedule-jobs/${id}`, method: 'GET'
    },
      options);
    }

/**
 * @summary Update a scheduled job
 */
const update1 = (
    id: number,
    updateScheduleJobRequest: UpdateScheduleJobRequest,
 options?: SecondParameter<typeof update1Mutator<ScheduleJobResult>>,) => {
      return update1Mutator<ScheduleJobResult>(
      {url: `/api/schedule-jobs/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateScheduleJobRequest
    },
      options);
    }

/**
 * @summary Delete a scheduled job
 */
const delete1 = (
    id: number,
 options?: SecondParameter<typeof delete1Mutator<void>>,) => {
      return delete1Mutator<void>(
      {url: `/api/schedule-jobs/${id}`, method: 'DELETE'
    },
      options);
    }

/**
 * @summary Get a pipeline by id
 */
const findById2 = (
    id: number,
 options?: SecondParameter<typeof findById2Mutator<PipelineResult>>,) => {
      return findById2Mutator<PipelineResult>(
      {url: `/api/pipelines/${id}`, method: 'GET'
    },
      options);
    }

/**
 * @summary Update a pipeline
 */
const update2 = (
    id: number,
    updatePipelineRequest: UpdatePipelineRequest,
 options?: SecondParameter<typeof update2Mutator<PipelineResult>>,) => {
      return update2Mutator<PipelineResult>(
      {url: `/api/pipelines/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updatePipelineRequest
    },
      options);
    }

/**
 * @summary Delete a pipeline
 */
const delete2 = (
    id: number,
 options?: SecondParameter<typeof delete2Mutator<void>>,) => {
      return delete2Mutator<void>(
      {url: `/api/pipelines/${id}`, method: 'DELETE'
    },
      options);
    }

/**
 * @summary Get a pipeline step by id
 */
const findById3 = (
    id: number,
 options?: SecondParameter<typeof findById3Mutator<PipelineStepResult>>,) => {
      return findById3Mutator<PipelineStepResult>(
      {url: `/api/pipeline-steps/${id}`, method: 'GET'
    },
      options);
    }

/**
 * @summary Update a pipeline step
 */
const update3 = (
    id: number,
    updatePipelineStepRequest: UpdatePipelineStepRequest,
 options?: SecondParameter<typeof update3Mutator<PipelineStepResult>>,) => {
      return update3Mutator<PipelineStepResult>(
      {url: `/api/pipeline-steps/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updatePipelineStepRequest
    },
      options);
    }

/**
 * @summary Delete a pipeline step
 */
const delete3 = (
    id: number,
 options?: SecondParameter<typeof delete3Mutator<void>>,) => {
      return delete3Mutator<void>(
      {url: `/api/pipeline-steps/${id}`, method: 'DELETE'
    },
      options);
    }

/**
 * @summary Get a job execution by id
 */
const findById4 = (
    id: number,
 options?: SecondParameter<typeof findById4Mutator<JobExecutionResult>>,) => {
      return findById4Mutator<JobExecutionResult>(
      {url: `/api/job-executions/${id}`, method: 'GET'
    },
      options);
    }

/**
 * @summary Update a job execution
 */
const update4 = (
    id: number,
    updateJobExecutionRequest: UpdateJobExecutionRequest,
 options?: SecondParameter<typeof update4Mutator<JobExecutionResult>>,) => {
      return update4Mutator<JobExecutionResult>(
      {url: `/api/job-executions/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateJobExecutionRequest
    },
      options);
    }

/**
 * @summary Delete a job execution
 */
const delete4 = (
    id: number,
 options?: SecondParameter<typeof delete4Mutator<void>>,) => {
      return delete4Mutator<void>(
      {url: `/api/job-executions/${id}`, method: 'DELETE'
    },
      options);
    }

/**
 * @summary Get an email template by id
 */
const findById5 = (
    id: number,
 options?: SecondParameter<typeof findById5Mutator<EmailTemplateResult>>,) => {
      return findById5Mutator<EmailTemplateResult>(
      {url: `/api/email-templates/${id}`, method: 'GET'
    },
      options);
    }

/**
 * @summary Update an email template
 */
const update5 = (
    id: number,
    updateEmailTemplateRequest: UpdateEmailTemplateRequest,
 options?: SecondParameter<typeof update5Mutator<EmailTemplateResult>>,) => {
      return update5Mutator<EmailTemplateResult>(
      {url: `/api/email-templates/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateEmailTemplateRequest
    },
      options);
    }

/**
 * @summary Delete an email template
 */
const delete5 = (
    id: number,
 options?: SecondParameter<typeof delete5Mutator<void>>,) => {
      return delete5Mutator<void>(
      {url: `/api/email-templates/${id}`, method: 'DELETE'
    },
      options);
    }

/**
 * @summary Get a connection definition by id
 */
const findById6 = (
    id: number,
 options?: SecondParameter<typeof findById6Mutator<ConnectionResult>>,) => {
      return findById6Mutator<ConnectionResult>(
      {url: `/api/connection-definitions/${id}`, method: 'GET'
    },
      options);
    }

/**
 * @summary Update a connection definition
 */
const update6 = (
    id: number,
    updateConnectionRequest: UpdateConnectionRequest,
 options?: SecondParameter<typeof update6Mutator<ConnectionResult>>,) => {
      return update6Mutator<ConnectionResult>(
      {url: `/api/connection-definitions/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateConnectionRequest
    },
      options);
    }

/**
 * @summary Delete a connection definition
 */
const delete6 = (
    id: number,
 options?: SecondParameter<typeof delete6Mutator<void>>,) => {
      return delete6Mutator<void>(
      {url: `/api/connection-definitions/${id}`, method: 'DELETE'
    },
      options);
    }

/**
 * @summary List service definitions
 */
const findAll = (
    params?: FindAllParams,
 options?: SecondParameter<typeof findAllMutator<PageServiceResult>>,) => {
      return findAllMutator<PageServiceResult>(
      {url: `/api/service-definitions`, method: 'GET',
        params
    },
      options);
    }

/**
 * @summary Create a service definition
 */
const create = (
    createServiceRequest: CreateServiceRequest,
 options?: SecondParameter<typeof createMutator<ServiceResult>>,) => {
      return createMutator<ServiceResult>(
      {url: `/api/service-definitions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createServiceRequest
    },
      options);
    }

/**
 * @summary List scheduled jobs
 */
const findAll1 = (
    params?: FindAll1Params,
 options?: SecondParameter<typeof findAll1Mutator<PageScheduleJobResult>>,) => {
      return findAll1Mutator<PageScheduleJobResult>(
      {url: `/api/schedule-jobs`, method: 'GET',
        params
    },
      options);
    }

/**
 * @summary Create a scheduled job
 */
const create1 = (
    createScheduleJobRequest: CreateScheduleJobRequest,
 options?: SecondParameter<typeof create1Mutator<ScheduleJobResult>>,) => {
      return create1Mutator<ScheduleJobResult>(
      {url: `/api/schedule-jobs`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createScheduleJobRequest
    },
      options);
    }

/**
 * @summary List pipelines
 */
const findAll2 = (
    params?: FindAll2Params,
 options?: SecondParameter<typeof findAll2Mutator<PagePipelineResult>>,) => {
      return findAll2Mutator<PagePipelineResult>(
      {url: `/api/pipelines`, method: 'GET',
        params
    },
      options);
    }

/**
 * @summary Create a pipeline
 */
const create2 = (
    createPipelineRequest: CreatePipelineRequest,
 options?: SecondParameter<typeof create2Mutator<PipelineResult>>,) => {
      return create2Mutator<PipelineResult>(
      {url: `/api/pipelines`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPipelineRequest
    },
      options);
    }

/**
 * @summary List pipeline steps
 */
const findAll3 = (
    params?: FindAll3Params,
 options?: SecondParameter<typeof findAll3Mutator<PagePipelineStepResult>>,) => {
      return findAll3Mutator<PagePipelineStepResult>(
      {url: `/api/pipeline-steps`, method: 'GET',
        params
    },
      options);
    }

/**
 * @summary Create a pipeline step
 */
const create3 = (
    createPipelineStepRequest: CreatePipelineStepRequest,
 options?: SecondParameter<typeof create3Mutator<PipelineStepResult>>,) => {
      return create3Mutator<PipelineStepResult>(
      {url: `/api/pipeline-steps`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPipelineStepRequest
    },
      options);
    }

/**
 * @summary List job executions
 */
const findAll4 = (
    params?: FindAll4Params,
 options?: SecondParameter<typeof findAll4Mutator<PageJobExecutionResult>>,) => {
      return findAll4Mutator<PageJobExecutionResult>(
      {url: `/api/job-executions`, method: 'GET',
        params
    },
      options);
    }

/**
 * @summary Create a job execution
 */
const create4 = (
    createJobExecutionRequest: CreateJobExecutionRequest,
 options?: SecondParameter<typeof create4Mutator<JobExecutionResult>>,) => {
      return create4Mutator<JobExecutionResult>(
      {url: `/api/job-executions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createJobExecutionRequest
    },
      options);
    }

/**
 * @summary Execute a service
 */
const execute = (
    appId: string,
    serviceCode: string,
    serviceVersion: string,
    executeServiceRequest?: ExecuteServiceRequest,
 options?: SecondParameter<typeof executeMutator<ExecuteServiceResponse>>,) => {
      return executeMutator<ExecuteServiceResponse>(
      {url: `/api/execute/${appId}/${serviceCode}/${serviceVersion}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: executeServiceRequest
    },
      options);
    }

/**
 * @summary List email templates
 */
const findAll5 = (
    params?: FindAll5Params,
 options?: SecondParameter<typeof findAll5Mutator<PageEmailTemplateResult>>,) => {
      return findAll5Mutator<PageEmailTemplateResult>(
      {url: `/api/email-templates`, method: 'GET',
        params
    },
      options);
    }

/**
 * @summary Create an email template
 */
const create5 = (
    createEmailTemplateRequest: CreateEmailTemplateRequest,
 options?: SecondParameter<typeof create5Mutator<EmailTemplateResult>>,) => {
      return create5Mutator<EmailTemplateResult>(
      {url: `/api/email-templates`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createEmailTemplateRequest
    },
      options);
    }

/**
 * @summary List connection definitions
 */
const findAll6 = (
    params?: FindAll6Params,
 options?: SecondParameter<typeof findAll6Mutator<PageConnectionResult>>,) => {
      return findAll6Mutator<PageConnectionResult>(
      {url: `/api/connection-definitions`, method: 'GET',
        params
    },
      options);
    }

/**
 * @summary Create a connection definition
 */
const create6 = (
    createConnectionRequest: CreateConnectionRequest,
 options?: SecondParameter<typeof create6Mutator<ConnectionResult>>,) => {
      return create6Mutator<ConnectionResult>(
      {url: `/api/connection-definitions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createConnectionRequest
    },
      options);
    }

/**
 * @summary Get a service definition schema
 */
const getSchema = (
    serviceType: 'REST' | 'DB' | 'PIPELINE' | 'EMAIL',
 options?: SecondParameter<typeof getSchemaMutator<GetSchema200>>,) => {
      return getSchemaMutator<GetSchema200>(
      {url: `/api/service-definition-schemas/${serviceType}`, method: 'GET'
    },
      options);
    }

/**
 * @summary List logs
 */
const findAll7 = (
    params?: FindAll7Params,
 options?: SecondParameter<typeof findAll7Mutator<PageLogResult>>,) => {
      return findAll7Mutator<PageLogResult>(
      {url: `/api/logs`, method: 'GET',
        params
    },
      options);
    }

/**
 * @summary Get a log entry
 */
const findById7 = (
    id: number,
 options?: SecondParameter<typeof findById7Mutator<LogResult>>,) => {
      return findById7Mutator<LogResult>(
      {url: `/api/logs/${id}`, method: 'GET'
    },
      options);
    }

/**
 * @summary List all enum options
 */
const findAll8 = (

 options?: SecondParameter<typeof findAll8Mutator<FindAll8200>>,) => {
      return findAll8Mutator<FindAll8200>(
      {url: `/api/enums`, method: 'GET'
    },
      options);
    }

/**
 * @summary List options for a single enum
 */
const findByName = (
    enumName: string,
 options?: SecondParameter<typeof findByNameMutator<EnumOptionResponse[]>>,) => {
      return findByNameMutator<EnumOptionResponse[]>(
      {url: `/api/enums/${enumName}`, method: 'GET'
    },
      options);
    }

/**
 * @summary Get a connection configuration schema
 */
const getSchema1 = (
    connectionType: 'DB' | 'REST' | 'SOAP' | 'SFTP' | 'SMTP' | 'KAFKA',
 options?: SecondParameter<typeof getSchema1Mutator<GetSchema1200>>,) => {
      return getSchema1Mutator<GetSchema1200>(
      {url: `/api/connection-definition-schemas/${connectionType}`, method: 'GET'
    },
      options);
    }

return {findById,update,_delete,findById1,update1,delete1,findById2,update2,delete2,findById3,update3,delete3,findById4,update4,delete4,findById5,update5,delete5,findById6,update6,delete6,findAll,create,findAll1,create1,findAll2,create2,findAll3,create3,findAll4,create4,execute,findAll5,create5,findAll6,create6,getSchema,findAll7,findById7,findAll8,findByName,getSchema1}};
export type FindByIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEConnectorAPI>['findById']>>>
export type UpdateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEConnectorAPI>['update']>>>
export type _DeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEConnectorAPI>['_delete']>>>
export type FindById1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getEConnectorAPI>['findById1']>>>
export type Update1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getEConnectorAPI>['update1']>>>
export type Delete1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getEConnectorAPI>['delete1']>>>
export type FindById2Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getEConnectorAPI>['findById2']>>>
export type Update2Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getEConnectorAPI>['update2']>>>
export type Delete2Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getEConnectorAPI>['delete2']>>>
export type FindById3Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getEConnectorAPI>['findById3']>>>
export type Update3Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getEConnectorAPI>['update3']>>>
export type Delete3Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getEConnectorAPI>['delete3']>>>
export type FindById4Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getEConnectorAPI>['findById4']>>>
export type Update4Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getEConnectorAPI>['update4']>>>
export type Delete4Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getEConnectorAPI>['delete4']>>>
export type FindById5Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getEConnectorAPI>['findById5']>>>
export type Update5Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getEConnectorAPI>['update5']>>>
export type Delete5Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getEConnectorAPI>['delete5']>>>
export type FindById6Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getEConnectorAPI>['findById6']>>>
export type Update6Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getEConnectorAPI>['update6']>>>
export type Delete6Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getEConnectorAPI>['delete6']>>>
export type FindAllResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEConnectorAPI>['findAll']>>>
export type CreateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEConnectorAPI>['create']>>>
export type FindAll1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getEConnectorAPI>['findAll1']>>>
export type Create1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getEConnectorAPI>['create1']>>>
export type FindAll2Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getEConnectorAPI>['findAll2']>>>
export type Create2Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getEConnectorAPI>['create2']>>>
export type FindAll3Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getEConnectorAPI>['findAll3']>>>
export type Create3Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getEConnectorAPI>['create3']>>>
export type FindAll4Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getEConnectorAPI>['findAll4']>>>
export type Create4Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getEConnectorAPI>['create4']>>>
export type ExecuteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEConnectorAPI>['execute']>>>
export type FindAll5Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getEConnectorAPI>['findAll5']>>>
export type Create5Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getEConnectorAPI>['create5']>>>
export type FindAll6Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getEConnectorAPI>['findAll6']>>>
export type Create6Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getEConnectorAPI>['create6']>>>
export type GetSchemaResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEConnectorAPI>['getSchema']>>>
export type FindAll7Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getEConnectorAPI>['findAll7']>>>
export type FindById7Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getEConnectorAPI>['findById7']>>>
export type FindAll8Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getEConnectorAPI>['findAll8']>>>
export type FindByNameResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEConnectorAPI>['findByName']>>>
export type GetSchema1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getEConnectorAPI>['getSchema1']>>>
