apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: discovery-server-staging
  namespace: argocd

spec:
  project: backend-services

  source:
    repoURL: https://github.com/nguyenngocvien/business-workflow-automation.git
    targetRevision: main
    path: gitops/apps/discovery-server

    helm:
      valueFiles:
        - ../../environments/staging/discovery-server/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: staging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
