apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: document-service-dev
  namespace: argocd

spec:
  project: backend-services

  source:
    repoURL: https://github.com/nguyenngocvien/business-workflow-automation.git
    targetRevision: main
    path: gitops/apps/document-service

    helm:
      valueFiles:
        - ../../environments/dev/document-service/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
