apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: workflow-service-staging
  namespace: argocd

spec:
  project: backend-services

  source:
    repoURL: https://github.com/nguyenngocvien/business-workflow-automation.git
    targetRevision: main
    path: gitops/apps/workflow-service

    helm:
      valueFiles:
        - ../../environments/staging/workflow-service/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: staging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
